"""the system shall store an access token with its token value and expires_at and return it by id.

Generated by The Factory from its requirement graph.
"""

import json
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

import telemetry
from store import StoreUnavailable, open_store
from store import counters as store_counters

SERVICE_NAME = 'access'
SERVICE_VERSION = "1.0.0"
# What the graph calls the thing this component is about, and where it lives.
# Telemetry is labelled with them so a metric joins back to the requirements it
# serves (docs/15 §1) — the same names `graph.subjects` indexes, because two
# derivations of one name is how a join quietly stops finding anything.
ENTITY = 'acce'
BASE_PATH = '/access'
# How long a record is kept, from the requirement's retention answer. None means
# forever. The store sweeps on read; no handler has to remember.
RETENTION_DAYS = 30
# Columns derived from what the requirements named (docs/11 §4). The record is
# stored whole either way; these let the database be queried through them.
RECORD_FIELDS = ['token_value', 'expires_at']
# How many times the store tries before giving up. More than one only when a
# requirement answered "retry, then reject" — the retry-with-backoff Pattern.
STORE_ATTEMPTS = 3
# The fields the requirement named, and what each must hold. Enforced in the
# plumbing rather than asked of the handler: validation is derivable from the
# contract, and a check that is derivable is the factory's to make. "Any JSON
# object" was honest for a factory that could not type anything — and it is
# why nothing could ever verify that an amount was an amount.
REQUIRED_FIELDS = ['token_value', 'expires_at']
FIELD_TYPES = {'expires_at': 'date-time'}
# How a major-unit amount becomes integer minor units, from Q-1000. None means
# integer fields refuse every non-int. With a mode set, a float is accepted and
# normalised here so create() stores what the criteria expect without rewriting
# this method.
AMOUNT_ROUNDING = None
# Other services this record points at. Enforced in the plumbing: a body that
# names a {resource}_id for a record that was never stored is refused the
# same way a missing field is — before the handler runs. Stage 2 of relations
# (docs/06 §3): the graph edge alone was a note; this is the foreign key.
REFERENCES = []
OWNER_HEADER = 'X-Owner'

# Where this component's records live. Provided by the scaffold: put a record
# with store.put(record, owner), read one with store.get(id), list them with
# store.list(owner). Do not hold records in a module-level dict — records must reach the database or they are lost when the process stops, which is the one thing this scaffold exists to prevent.
store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS)


class Handler(BaseHTTPRequestHandler):
    """One method per operation in the contract. The plumbing is done."""

    # -- plumbing: correct, and not yours to change ------------------------

    def log_message(self, *args):
        pass

    def _send(self, status, payload=None):
        # 204 means "no content", and a 204 carrying a JSON body is a malformed
        # response that some clients accept and some hang on. The plumbing
        # handles it so no handler has to remember.
        body = b"" if status == 204 else json.dumps(payload).encode()
        self.send_response(status)
        if body:
            self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if body:
            self.wfile.write(body)
        # One counter per outcome, named the same way in every component
        # (docs/15 §2). In the plumbing rather than in a handler, so it counts
        # whatever the component answers including the answers it did not mean.
        telemetry.count(f"http_{status}")
        # And per contract operation, which is the anchor of the requirement
        # join (docs/15 §1, §2): operations are named by contracts, contracts
        # are edges in the graph, so a burn traces back to the requirements it
        # serves without anybody maintaining a naming convention. The label set
        # is a literal, so cardinality is bounded by the Pattern rather than by
        # whatever a handler decides to pass.
        operation = self._operation()
        if operation:
            telemetry.count(f"{operation}.{'error' if status >= 400 else 'ok'}")

    def _operation(self):
        """Which contract operation this request is, as the graph names it."""
        tail = self.path.rstrip("/").rsplit("/", 1)[-1]
        collection = ("/" + tail) == BASE_PATH or not tail
        verb = {"POST": "store", "PUT": "store", "DELETE": "delete"}.get(
            self.command, "list" if collection else "read"
        )
        return f"{ENTITY}.{verb}" if ENTITY else ""

    def _body(self) -> dict:
        # Parsed once and remembered: the stream can only be read once, and
        # the plumbing validates the same bytes the handler then stores.
        if not hasattr(self, "_parsed_body"):
            length = int(self.headers.get("Content-Length") or 0)
            if not length:
                self._parsed_body = {}
            else:
                try:
                    self._parsed_body = json.loads(self.rfile.read(length) or b"{}")
                except ValueError:
                    self._parsed_body = {}
        return self._parsed_body

    def _malformed(self):
        """What is wrong with this body, or None. The error names the field.

        In the plumbing because it is derived from the contract: the required
        fields are the requirement's own "with its …" clause, and the types
        come from what the names declare. A handler never sees a body that
        fails its contract.
        """
        body = self._body()
        if not isinstance(body, dict):
            return {"error": "the body must be a JSON object"}
        missing = [name for name in REQUIRED_FIELDS if name not in body]
        if missing:
            return {"error": "missing required field(s): " + ", ".join(missing),
                    "fields": missing}
        for name, kind in FIELD_TYPES.items():
            if name not in body:
                continue
            value = body[name]
            if kind == "integer":
                # Booleans are a subclass of int in Python; refuse them either way.
                if isinstance(value, bool):
                    return {"error": f"{name} must be a whole number"}
                if AMOUNT_ROUNDING:
                    # Q-1000: major-unit floats are accepted and normalised below.
                    if not isinstance(value, (int, float)):
                        return {"error": f"{name} must be a whole number"}
                elif not isinstance(value, int):
                    return {"error": f"{name} must be a whole number"}
            if kind == "date-time":
                from datetime import datetime

                try:
                    datetime.fromisoformat(str(value))
                except ValueError:
                    return {"error": f"{name} must be an ISO 8601 date-time"}
        if AMOUNT_ROUNDING:
            # Major units → integer minor units before the handler runs, so the
            # agent stores the body as given and the half-up / bankers criterion
            # still holds. An int is already minor units and is left alone.
            from decimal import ROUND_HALF_EVEN, ROUND_HALF_UP, Decimal

            mode = (ROUND_HALF_UP if AMOUNT_ROUNDING == "half_up"
                    else ROUND_HALF_EVEN)
            for name, kind in FIELD_TYPES.items():
                if kind != "integer" or name not in body:
                    continue
                value = body[name]
                if isinstance(value, float):
                    body[name] = int(
                        (Decimal(str(value)) * 100).to_integral_value(rounding=mode)
                    )
        # A reference names a record in another service's store. Look it up
        # in-process rather than over HTTP: stage 2 seeds the sibling schema
        # beside this component; stage 4 (multi-component) is when the other
        # service answers on its own port.
        for ref in REFERENCES:
            field = ref.get("field")
            service = ref.get("service")
            if not field or not service or field not in body:
                continue
            if open_store(service).get(str(body[field])) is None:
                return {"error": f"{field} names a {ref.get('resource', 'record')} "
                                f"that was never stored",
                        "fields": [field]}
        return None

    def _caller(self) -> str:
        return self.headers.get('X-Owner', "") if 'X-Owner' else ""

    def _path_id(self) -> str:
        return self.path.rstrip("/").rsplit("/", 1)[-1]

    def do_GET(self):
        self._route("GET")

    def do_POST(self):
        self._route("POST")

    def do_PUT(self):
        self._route("PUT")

    def do_DELETE(self):
        self._route("DELETE")

    def _route(self, method):
        # Any handler that raises would otherwise kill the connection and the
        # component would look unreachable rather than wrong.
        try:
            if method == "GET" and self.path.rstrip("/") == "/health":
                return self.health()
            if method == "POST" and self.path.rstrip("/") == '/access':
                if not self._caller():
                    return self._send(401, {"error": "an owner is required"})
                problem = self._malformed()
                if problem is not None:
                    return self._send(400, problem)
                return self.create()
            if method == "GET" and self.path.startswith('/access/'):
                if not self._caller():
                    return self._send(401, {"error": "an owner is required"})
                return self.fetch(self._path_id())
            self._send(404, {"error": "not found"})
        except StoreUnavailable as error:
            # The dependency is down, which is not this component being wrong.
            # 503 rather than 500 so a caller can tell "try again" from "this
            # request will never work" — and so the criterion a requirement
            # derives about a failed dependency has something to assert.
            self._send(503, {"error": str(error)})
        except Exception as error:  # noqa: BLE001
            self._send(500, {"error": str(error)})

    # -- the behaviour: this is the part you implement ---------------------

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        self._send(200, {"service": SERVICE_NAME, "version": SERVICE_VERSION,
                         # What this component has done, so behaviour invisible
                         # from a single response — a retry, a refusal — can
                         # still be seen.
                         "counters": dict(telemetry.snapshot(), **store_counters)})

    def create(self):
        """store the body as it was sent and answer 201 with the record.

        The contract names no required field, so require none here: a component
        that insists on one refuses requests the criteria expect it to accept.
        Validation lives in the plumbing (`_malformed`), which runs before this
        method, so by the time we get here the body is a JSON object with every
        typed field correctly typed.

        Store it unchanged with `store.put(record, owner)`, which fills in "id"
        and "owner" and returns what was stored — exactly the contract's 201
        response ("the fields that were sent, plus id and owner"). Every field
        the caller sent is echoed back, including any unknown one.
        """
        return self._send(201, store.put(self._body(), self._caller()))

    def fetch(self, record_id):
        """answer 200 with the record, 404 when there is none, and 403 when the caller is not the record's owner.

        Fetch first: a record that was never created (or has since expired past
        retention) reads back as None, which is 404 — not "no owner", so an
        unknown id must not be answered 403. Only once we know it exists do we
        consult `store.owner_of`, and only then can a wrong caller be refused 403.

        The store sweeps expired records on read (`_expire`), so by the time this
        runs a record past its retention is gone from the database and reads back
        as None — which is exactly "hard deleted" (AC-1470).
        """
        record = store.get(record_id)
        if record is None:
            return self._send(404, {"error": "no such record"})
        owner = store.owner_of(record_id)
        if not owner or owner != self._caller():
            return self._send(403, {"error": "not the owner of this record"})
        return self._send(200, record)


def serve(port):
    ThreadingHTTPServer(("127.0.0.1", port), Handler).serve_forever()


if __name__ == "__main__":
    serve(8080)
