"""Factory Test 4: every component of this application, behind one port.

Generated by The Factory from its requirement graph. Not edited by hand.
"""

import json
import os

import flags
import uvicorn
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from foundation import router as foundation_router
from oauth import router as oauth_router
from oauth_clients import router as oauth_clients_router
from runnables import router as runnables_router
from users import router as users_router

SERVICE_NAME = 'Factory Test 4'
SERVICE_VERSION = "1.0.0"
PORT = int(os.environ.get("PORT", "8080"))

COMPONENTS = [
    {"service": 'foundation', "base_path": '/foundation', "routes": [('GET', '^/foundation/?$', '')]},
    {"service": 'oauth', "base_path": '/oauth', "routes": [('GET', '^/oauth/authorize/?$', 'flag.r_1303'), ('GET', '^/oauth/health/?$', 'flag.f_1313'), ('POST', '^/oauth/token/?$', 'flag.f_1313')]},
    {"service": 'oauth_clients', "base_path": '/oauth/clients', "routes": [('POST', '^/oauth/clients/?$', 'flag.r_1302'), ('GET', '^/oauth/clients/[^/]+/?$', 'flag.r_1302')]},
    {"service": 'runnables', "base_path": '/runnables', "routes": [('POST', '^/runnables/?$', 'flag.r_1301'), ('GET', '^/runnables/[^/]+/?$', 'flag.r_1301')]},
    {"service": 'users', "base_path": '/users', "routes": [('POST', '^/users/?$', 'flag.f_1316'), ('GET', '^/users/[^/]+/?$', 'flag.f_1316')]},
]

app = FastAPI(title=SERVICE_NAME, version=SERVICE_VERSION)
app.include_router(foundation_router)
app.include_router(oauth_router)
app.include_router(oauth_clients_router)
app.include_router(runnables_router)
app.include_router(users_router)


@app.get("/health")
async def application_health():
    return {
        "service": SERVICE_NAME,
        "version": SERVICE_VERSION,
        "components": [component["service"] for component in COMPONENTS],
        "flags": flags.all_on(),
    }


@app.middleware("http")
async def enforce_flags(request: Request, call_next):
    path = request.url.path.split("?", 1)[0]
    for component in COMPONENTS:
        base = component["base_path"]
        if path != base and not path.startswith(base + "/"):
            continue
        for verb, pattern, flag in component["routes"]:
            import re
            if request.method != verb or not re.match(pattern, path):
                continue
            if flag and not flags.on(flag):
                return JSONResponse(status_code=404, content={"error": "not found"})
            break
    return await call_next(request)


if __name__ == "__main__":
    print(json.dumps({
        "service": SERVICE_NAME,
        "port": PORT,
        "components": [c["service"] for c in COMPONENTS],
        "flags_on": flags.all_on(),
    }))
    uvicorn.run(app, host="0.0.0.0", port=PORT)
