"""Factory Test Live: every component of this application, behind one port.

Generated by The Factory from its requirement graph. Not edited by hand.
"""

import json
import os

import flags
import uvicorn
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from drops_cleanup import router as drops_cleanup_router
from foundation import router as foundation_router
from notifications_stream import router as notifications_stream_router
from webhooks import router as webhooks_router

SERVICE_NAME = 'Factory Test Live'
SERVICE_VERSION = "1.0.0"
PORT = int(os.environ.get("PORT", "8080"))

COMPONENTS = [
    {"service": 'drops_cleanup', "base_path": '/drops', "routes": [('POST', '^/drops/cleanup/?$', 'flag.f_1428')]},
    {"service": 'foundation', "base_path": '/foundation', "routes": [('GET', '^/foundation/?$', '')]},
    {"service": 'notifications_stream', "base_path": '/notifications', "routes": [('GET', '^/notifications/stream/?$', 'flag.r_1414')]},
    {"service": 'webhooks', "base_path": '/webhooks', "routes": [('POST', '^/webhooks//?$', 'flag.r_1408')]},
]

app = FastAPI(title=SERVICE_NAME, version=SERVICE_VERSION)


@app.get("/health")
async def application_health():
    return {
        "service": SERVICE_NAME,
        "version": SERVICE_VERSION,
        "components": [component["service"] for component in COMPONENTS],
        "flags": flags.all_on(),
    }


# Component routers after /health so a component's own /health does not shadow
# the application one (W-1313: forums /health won and hid the real surface).
app.include_router(drops_cleanup_router)
app.include_router(foundation_router)
app.include_router(notifications_stream_router)
app.include_router(webhooks_router)


@app.middleware("http")
async def enforce_flags(request: Request, call_next):
    path = request.url.path.split("?", 1)[0]
    for component in COMPONENTS:
        base = component["base_path"]
        if path != base and not path.startswith(base + "/"):
            continue
        for verb, pattern, flag in component["routes"]:
            import re
            if request.method != verb or not re.match(pattern, path):
                continue
            if flag and not flags.on(flag):
                return JSONResponse(status_code=404, content={"error": "not found"})
            break
    return await call_next(request)


if __name__ == "__main__":
    print(json.dumps({
        "service": SERVICE_NAME,
        "port": PORT,
        "components": [c["service"] for c in COMPONENTS],
        "flags_on": flags.all_on(),
    }))
    uvicorn.run(app, host="0.0.0.0", port=PORT)
