"""Factory Test 4: every component of this application, behind one port.

Generated by The Factory from its requirement graph. Not edited by hand.
"""

import json
import os

import flags
import uvicorn
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from exchanges import router as exchanges_router
from foundation import router as foundation_router
from fulls import router as fulls_router
from oauth import router as oauth_router
from posts import router as posts_router
from threads import router as threads_router
from titles import router as titles_router
from users import router as users_router
from ws import router as ws_router

SERVICE_NAME = 'Factory Test 4'
SERVICE_VERSION = "1.0.0"
PORT = int(os.environ.get("PORT", "8080"))

COMPONENTS = [
    {"service": 'exchanges', "base_path": '/exchanges', "routes": [('POST', '^/exchanges/?$', 'flag.r_1236')]},
    {"service": 'foundation', "base_path": '/foundation', "routes": [('GET', '^/foundation/?$', '')]},
    {"service": 'fulls', "base_path": '/fulls', "routes": [('GET', '^/fulls/domains/events/?$', 'flag.f_1263'), ('GET', '^/fulls/domains/events/?$', 'flag.f_1263')]},
    {"service": 'oauth', "base_path": '/oauth', "routes": [('GET', '^/oauth/authorize/?$', 'flag.r_1235'), ('POST', '^/oauth/token/?$', 'flag.r_1235')]},
    {"service": 'posts', "base_path": '/posts', "routes": [('POST', '^/posts/?$', 'flag.r_1240'), ('GET', '^/posts/[^/]+/?$', 'flag.r_1240')]},
    {"service": 'threads', "base_path": '/threads', "routes": [('POST', '^/threads/?$', 'flag.r_1239'), ('GET', '^/threads/[^/]+/?$', 'flag.r_1239')]},
    {"service": 'titles', "base_path": '/titles', "routes": [('POST', '^/titles/?$', 'flag.r_1238'), ('GET', '^/titles/[^/]+/?$', 'flag.r_1238')]},
    {"service": 'users', "base_path": '/users', "routes": [('POST', '^/users/?$', 'flag.r_1237'), ('GET', '^/users/[^/]+/?$', 'flag.r_1237')]},
    {"service": 'ws', "base_path": '/ws', "routes": [('GET', '^/ws/?$', 'flag.r_1241')]},
]

app = FastAPI(title=SERVICE_NAME, version=SERVICE_VERSION)
app.include_router(exchanges_router)
app.include_router(foundation_router)
app.include_router(fulls_router)
app.include_router(oauth_router)
app.include_router(posts_router)
app.include_router(threads_router)
app.include_router(titles_router)
app.include_router(users_router)
app.include_router(ws_router)


@app.get("/health")
async def application_health():
    return {
        "service": SERVICE_NAME,
        "version": SERVICE_VERSION,
        "components": [component["service"] for component in COMPONENTS],
        "flags": flags.all_on(),
    }


@app.middleware("http")
async def enforce_flags(request: Request, call_next):
    path = request.url.path.split("?", 1)[0]
    for component in COMPONENTS:
        base = component["base_path"]
        if path != base and not path.startswith(base + "/"):
            continue
        for verb, pattern, flag in component["routes"]:
            import re
            if request.method != verb or not re.match(pattern, path):
                continue
            if flag and not flags.on(flag):
                return JSONResponse(status_code=404, content={"error": "not found"})
            break
    return await call_next(request)


if __name__ == "__main__":
    print(json.dumps({
        "service": SERVICE_NAME,
        "port": PORT,
        "components": [c["service"] for c in COMPONENTS],
        "flags_on": flags.all_on(),
    }))
    uvicorn.run(app, host="0.0.0.0", port=PORT)
