"""the system shall store a bookmark with its url and a title and return it by id.

Generated by The Factory from its requirement graph.
"""

import json
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

from store import StoreUnavailable, open_store

SERVICE_NAME = 'bookmarks'
SERVICE_VERSION = "1.0.0"
# How long a record is kept, from the requirement's retention answer. None means
# forever. The store sweeps on read; no handler has to remember.
RETENTION_DAYS = 30
# Columns derived from what the requirements named (docs/11 §4). The record is
# stored whole either way; these let the database be queried through them.
RECORD_FIELDS = ['url', 'title']
OWNER_HEADER = 'X-Owner'

# Where this component's records live. Provided by the scaffold: put a record
# with store.put(record, owner), read one with store.get(id), list them with
# store.list(owner). Do not hold records in a module-level dict — records must reach the database or they are lost when the process stops, which is the one thing this scaffold exists to prevent.
store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS)


class Handler(BaseHTTPRequestHandler):
    """One method per operation in the contract. The plumbing is done."""

    # -- plumbing: correct, and not yours to change ------------------------

    def log_message(self, *args):
        pass

    def _send(self, status, payload=None):
        # 204 means "no content", and a 204 carrying a JSON body is a malformed
        # response that some clients accept and some hang on. The plumbing
        # handles it so no handler has to remember.
        body = b"" if status == 204 else json.dumps(payload).encode()
        self.send_response(status)
        if body:
            self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if body:
            self.wfile.write(body)

    def _body(self) -> dict:
        length = int(self.headers.get("Content-Length") or 0)
        if not length:
            return {}
        try:
            return json.loads(self.rfile.read(length) or b"{}")
        except ValueError:
            return {}

    def _caller(self) -> str:
        return self.headers.get('X-Owner', "") if 'X-Owner' else ""

    def _path_id(self) -> str:
        return self.path.rstrip("/").rsplit("/", 1)[-1]

    def do_GET(self):
        self._route("GET")

    def do_POST(self):
        self._route("POST")

    def do_PUT(self):
        self._route("PUT")

    def do_DELETE(self):
        self._route("DELETE")

    def _route(self, method):
        # Any handler that raises would otherwise kill the connection and the
        # component would look unreachable rather than wrong.
        try:
            if method == "GET" and self.path.rstrip("/") == "/health":
                return self.health()
            if method == "POST" and self.path.rstrip("/") == '/bookmarks':
                if not self._caller():
                    return self._send(401, {"error": "an owner is required"})
                return self.create()
            if method == "GET" and self.path.startswith('/bookmarks/'):
                if not self._caller():
                    return self._send(401, {"error": "an owner is required"})
                return self.fetch(self._path_id())
            self._send(404, {"error": "not found"})
        except StoreUnavailable as error:
            # The dependency is down, which is not this component being wrong.
            # 503 rather than 500 so a caller can tell "try again" from "this
            # request will never work" — and so the criterion a requirement
            # derives about a failed dependency has something to assert.
            self._send(503, {"error": str(error)})
        except Exception as error:  # noqa: BLE001
            self._send(500, {"error": str(error)})

    # -- the behaviour: this is the part you implement ---------------------

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        self._send(200, {"service": SERVICE_NAME, "version": SERVICE_VERSION})

    def create(self):
        """Store the body as it was sent and answer 201 with the record."""
        length = int(self.headers.get("Content-Length") or 0)
        if not length:
            record = {}
        else:
            try:
                raw = self.rfile.read(length)
                parsed = json.loads(raw)
            except (ValueError, TypeError):
                return self._send(400, {"error": "the body must be a JSON object"})
            if not isinstance(parsed, dict):
                return self._send(400, {"error": "the body must be a JSON object"})
            record = parsed

        stored = store.put(record, owner=self._caller())
        return self._send(201, stored)

    def fetch(self, record_id):
        """Answer 200 with the record, 404 when there is none, and 403 when the caller is not the record's owner."""
        record = store.get(record_id)
        if record is None:
            return self._send(404, {"error": "not found"})
        owner = store.owner_of(record_id)
        if owner != self._caller():
            return self._send(403, {"error": "forbidden"})
        return self._send(200, record)


def serve(port):
    ThreadingHTTPServer(("127.0.0.1", port), Handler).serve_forever()


if __name__ == "__main__":
    serve(8080)
