"""the system shall store a changelog note with its version and summary and return it by id.

Generated by The Factory from its requirement graph.
"""

import json
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

import telemetry
from store import StoreUnavailable, open_store
from store import counters as store_counters

SERVICE_NAME = 'changelogs'
SERVICE_VERSION = "1.0.0"
# What the graph calls the thing this component is about, and where it lives.
# Telemetry is labelled with them so a metric joins back to the requirements it
# serves (docs/15 §1) — the same names `graph.subjects` indexes, because two
# derivations of one name is how a join quietly stops finding anything.
ENTITY = 'changelog'
BASE_PATH = '/changelogs'
# How long a record is kept, from the requirement's retention answer. None means
# forever. The store sweeps on read; no handler has to remember.
RETENTION_DAYS = 30
# Columns derived from what the requirements named (docs/11 §4). The record is
# stored whole either way; these let the database be queried through them.
RECORD_FIELDS = ['version', 'summary']
# How many times the store tries before giving up. More than one only when a
# requirement answered "retry, then reject" — the retry-with-backoff Pattern.
STORE_ATTEMPTS = 3
OWNER_HEADER = 'X-Owner'

# Where this component's records live. Provided by the scaffold: put a record
# with store.put(record, owner), read one with store.get(id), list them with
# store.list(owner). Do not hold records in a module-level dict — records must reach the database or they are lost when the process stops, which is the one thing this scaffold exists to prevent.
store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS)


class Handler(BaseHTTPRequestHandler):
    """One method per operation in the contract. The plumbing is done."""

    # -- plumbing: correct, and not yours to change ------------------------

    def log_message(self, *args):
        pass

    def _send(self, status, payload=None):
        # 204 means "no content", and a 204 carrying a JSON body is a malformed
        # response that some clients accept and some hang on. The plumbing
        # handles it so no handler has to remember.
        body = b"" if status == 204 else json.dumps(payload).encode()
        self.send_response(status)
        if body:
            self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if body:
            self.wfile.write(body)
        # One counter per outcome, named the same way in every component
        # (docs/15 §2). In the plumbing rather than in a handler, so it counts
        # whatever the component answers including the answers it did not mean.
        telemetry.count(f"http_{status}")
        # And per contract operation, which is the anchor of the requirement
        # join (docs/15 §1, §2): operations are named by contracts, contracts
        # are edges in the graph, so a burn traces back to the requirements it
        # serves without anybody maintaining a naming convention. The label set
        # is a literal, so cardinality is bounded by the Pattern rather than by
        # whatever a handler decides to pass.
        operation = self._operation()
        if operation:
            telemetry.count(f"{operation}.{'error' if status >= 400 else 'ok'}")

    def _operation(self):
        """Which contract operation this request is, as the graph names it."""
        tail = self.path.rstrip("/").rsplit("/", 1)[-1]
        collection = ("/" + tail) == BASE_PATH or not tail
        verb = {"POST": "store", "PUT": "store", "DELETE": "delete"}.get(
            self.command, "list" if collection else "read"
        )
        return f"{ENTITY}.{verb}" if ENTITY else ""

    def _body(self) -> dict:
        length = int(self.headers.get("Content-Length") or 0)
        if not length:
            return {}
        try:
            return json.loads(self.rfile.read(length) or b"{}")
        except ValueError:
            return {}

    def _caller(self) -> str:
        return self.headers.get('X-Owner', "") if 'X-Owner' else ""

    def _path_id(self) -> str:
        return self.path.rstrip("/").rsplit("/", 1)[-1]

    def do_GET(self):
        self._route("GET")

    def do_POST(self):
        self._route("POST")

    def do_PUT(self):
        self._route("PUT")

    def do_DELETE(self):
        self._route("DELETE")

    def _route(self, method):
        # Any handler that raises would otherwise kill the connection and the
        # component would look unreachable rather than wrong.
        try:
            if method == "GET" and self.path.rstrip("/") == "/health":
                return self.health()
            if method == "POST" and self.path.rstrip("/") == '/changelogs':
                if not self._caller():
                    return self._send(401, {"error": "an owner is required"})
                return self.create()
            if method == "GET" and self.path.startswith('/changelogs/'):
                if not self._caller():
                    return self._send(401, {"error": "an owner is required"})
                return self.fetch(self._path_id())
            self._send(404, {"error": "not found"})
        except StoreUnavailable as error:
            # The dependency is down, which is not this component being wrong.
            # 503 rather than 500 so a caller can tell "try again" from "this
            # request will never work" — and so the criterion a requirement
            # derives about a failed dependency has something to assert.
            self._send(503, {"error": str(error)})
        except Exception as error:  # noqa: BLE001
            self._send(500, {"error": str(error)})

    # -- the behaviour: this is the part you implement ---------------------

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        self._send(200, {"service": SERVICE_NAME, "version": SERVICE_VERSION,
                         # What this component has done, so behaviour invisible
                         # from a single response — a retry, a refusal — can
                         # still be seen.
                         "counters": dict(telemetry.snapshot(), **store_counters)})

    def create(self):
        """store the body as it was sent and answer 201 with the record.

        Store every field the caller sent, unchanged, with
        `store.put(record, owner)` — which fills in "id" and "owner" and
        returns what was stored, which is exactly what the contract's 201
        response describes. Require no particular field: the contract names none, so a
        component that insists on one refuses requests the criteria expect it
        to accept. Refuse only a body that is not an object.
        """
        # Read (and thereby drain) the request body first; _body() returns {} for
        # an absent or empty body and parses JSON, so we must reject here anything
        # that parsed but was not an object — a string or a list.
        body = self._body()
        if not isinstance(body, dict):
            return self._send(400, {"error": "the body must be a JSON object"})
        stored = store.put(body, self._caller())
        return self._send(201, stored)

    def fetch(self, record_id):
        """answer 200 with the record, 404 when there is none, and 403 when the caller is not the record's owner.

        `store.get(record_id)` returns the record or None;
        `store.owner_of(record_id)` returns who stored it.
        """
        # A missing record is answered 404 for any identified caller before we can
        # even ask whether they own it — "no such record" and "not yours" are
        # different answers, and the contract lists them as separate responses.
        record = store.get(record_id)
        if record is None:
            return self._send(404, {"error": "no such record"})
        owner = store.owner_of(record_id) or ""
        caller = self._caller()
        if owner and caller and owner != caller:
            return self._send(403, {"error": "authorization error"})
        return self._send(200, record)


def serve(port):
    ThreadingHTTPServer(("127.0.0.1", port), Handler).serve_forever()


if __name__ == "__main__":
    serve(8080)
