"""the system shall store a memo and return it by id.

Generated by The Factory from its requirement graph.
"""

import json
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

SERVICE_NAME = 'memos'
SERVICE_VERSION = "1.0.0"
OWNER_HEADER = 'X-Owner'

# The records this component holds. Replace with whatever the requirement needs.
RECORDS: dict[str, dict] = {}
_next_id = [0]


def new_id() -> str:
    _next_id[0] += 1
    return str(_next_id[0])


class Handler(BaseHTTPRequestHandler):
    """One method per operation in the contract. The plumbing is done."""

    # -- plumbing: correct, and not yours to change ------------------------

    def log_message(self, *args):
        pass

    def _send(self, status, payload):
        body = json.dumps(payload).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _body(self) -> dict:
        length = int(self.headers.get("Content-Length") or 0)
        if not length:
            return {}
        try:
            return json.loads(self.rfile.read(length) or b"{}")
        except ValueError:
            return {}

    def _caller(self) -> str:
        return self.headers.get('X-Owner', "") if 'X-Owner' else ""

    def _path_id(self) -> str:
        return self.path.rstrip("/").rsplit("/", 1)[-1]

    def do_GET(self):
        self._route("GET")

    def do_POST(self):
        self._route("POST")

    def do_PUT(self):
        self._route("PUT")

    def do_DELETE(self):
        self._route("DELETE")

    def _route(self, method):
        # Any handler that raises would otherwise kill the connection and the
        # component would look unreachable rather than wrong.
        try:
            if method == "GET" and self.path.rstrip("/") == "/health":
                return self.health()
            if method == "POST" and self.path.rstrip("/") == '/memos':
                if not self._caller():
                    return self._send(401, {"error": "an owner is required"})
                return self.create()
            if method == "GET" and self.path.startswith('/memos/'):
                if not self._caller():
                    return self._send(401, {"error": "an owner is required"})
                return self.fetch(self._path_id())
            self._send(404, {"error": "not found"})
        except Exception as error:  # noqa: BLE001
            self._send(500, {"error": str(error)})

    # -- the behaviour: this is the part you implement ---------------------

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        self._send(200, {"service": SERVICE_NAME, "version": SERVICE_VERSION})

    def create(self):
        body = self._body()
        if not isinstance(body, dict):
            return self._send(400, {"error": "the body must be an object"})

        now = time.time()
        cutoff = now - 30 * 24 * 60 * 60
        for key in list(RECORDS.keys()):
            rec = RECORDS[key]
            if isinstance(rec, dict) and "created_at" in rec:
                if rec["created_at"] < cutoff:
                    del RECORDS[key]

        record = {**body, "id": new_id(), "owner": self._caller()}
        record["created_at"] = now
        RECORDS[record["id"]] = record
        return self._send(201, record)

    def fetch(self, record_id):
        now = time.time()
        cutoff = now - 30 * 24 * 60 * 60
        for key in list(RECORDS.keys()):
            rec = RECORDS[key]
            if isinstance(rec, dict) and "created_at" in rec:
                if rec["created_at"] < cutoff:
                    del RECORDS[key]

        record = RECORDS.get(record_id)
        if not record:
            return self._send(404, {"error": "not found"})
        if self._caller() != record["owner"]:
            return self._send(403, {"error": "forbidden"})
        return self._send(200, record)


def serve(port):
    ThreadingHTTPServer(("127.0.0.1", port), Handler).serve_forever()


if __name__ == "__main__":
    serve(8080)
