"""the system shall store a note and return it by id.

Generated by The Factory from its requirement graph.
"""

import json
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import time as _time

SERVICE_NAME = 'notes'
SERVICE_VERSION = "1.0.0"
OWNER_HEADER = 'X-Owner'

# The records this component holds. Replace with whatever the requirement needs.
RECORDS: dict[str, dict] = {}
_next_id = [0]


def new_id() -> str:
    _next_id[0] += 1
    return str(_next_id[0])


class Handler(BaseHTTPRequestHandler):
    """One method per operation in the contract. The plumbing is done."""

    # -- plumbing: correct, and not yours to change ------------------------

    def log_message(self, *args):
        pass

    def _send(self, status, payload):
        body = json.dumps(payload).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _body(self) -> dict:
        length = int(self.headers.get("Content-Length") or 0)
        if not length:
            return {}
        try:
            return json.loads(self.rfile.read(length) or b"{}")
        except ValueError:
            return {}

    def _caller(self) -> str:
        return self.headers.get('X-Owner', "") if 'X-Owner' else ""

    def _path_id(self) -> str:
        return self.path.rstrip("/").rsplit("/", 1)[-1]

    def do_GET(self):
        self._route("GET")

    def do_POST(self):
        self._route("POST")

    def do_PUT(self):
        self._route("PUT")

    def do_DELETE(self):
        self._route("DELETE")

    def _route(self, method):
        # Any handler that raises would otherwise kill the connection and the
        # component would look unreachable rather than wrong.
        try:
            if method == "GET" and self.path.rstrip("/") == "/health":
                return self.health()
            if method == "POST" and self.path.rstrip("/") == '/notes':
                if not self._caller():
                    return self._send(401, {"error": "an owner is required"})
                return self.create()
            if method == "GET" and self.path.startswith('/notes/'):
                if not self._caller():
                    return self._send(401, {"error": "an owner is required"})
                return self.fetch(self._path_id())
            self._send(404, {"error": "not found"})
        except Exception as error:  # noqa: BLE001
            self._send(500, {"error": str(error)})

    # -- the behaviour: this is the part you implement ---------------------

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        self._send(200, {"service": SERVICE_NAME, "version": SERVICE_VERSION})

    def create(self):
        """Store what the caller sent and answer 201 with the record."""
        now = _time.time()
        cutoff = now - 30 * 86400
        for rid, rec in list(RECORDS.items()):
            if "created_at" not in rec or rec["created_at"] < cutoff:
                del RECORDS[rid]
        record = self._body()
        record["id"] = new_id()
        record["owner"] = self._caller()
        record["created_at"] = now
        RECORDS[record["id"]] = record
        return self._send(201, record)

    def fetch(self, record_id):
        """Return 200 with the record, 403 when the caller is not the owner, and 404 when there is none."""
        now = _time.time()
        cutoff = now - 30 * 86400
        for rid, rec in list(RECORDS.items()):
            if "created_at" not in rec or rec["created_at"] < cutoff:
                del RECORDS[rid]
        record = RECORDS.get(record_id)
        if record is None:
            return self._send(404, {"error": "not found"})
        if record["owner"] != self._caller():
            return self._send(403, {"error": "forbidden"})
        return self._send(200, record)


def serve(port):
    ThreadingHTTPServer(("127.0.0.1", port), Handler).serve_forever()


if __name__ == "__main__":
    serve(8080)
