"""the system shall exchange a valid authorization code for an access token, enforce single-use semantics, and reject invalid or expired codes with HTTP 400.

Generated by The Factory from its requirement graph.
"""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse, Response

import threading
import uuid

import telemetry
from store import StoreUnavailable, open_store
from store import clock
from store import counters as store_counters
from oauth2_authorization_code import TOKEN_TYPE

# R-1235.143: an authorization code is single-use and short-lived — valid for
# ten minutes after it was issued, then rejected like any other bad grant.
CODE_LIFETIME_SECONDS = 600
# Decided default (intake Q-1004): the issued access token lives one hour.
ACCESS_TOKEN_TTL_SECONDS = 3600

SERVICE_NAME = 'exchanges'
SERVICE_VERSION = "1.0.0"
ENTITY = 'exchange'
BASE_PATH = '/exchanges'
RETENTION_DAYS = None
RECORD_FIELDS = ['access_token', 'token_type', 'scope']
STORE_ATTEMPTS = 1
REQUIRED_FIELDS = []
FIELD_TYPES = {}
AMOUNT_ROUNDING = None
REFERENCES = []
AUTH_SCHEME = 'plain'

store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS)


class Handler:
    """Contract plumbing and behaviour handlers. Complete the TODO methods only."""

    def __init__(self, request: Request):
        self.request = request
        self._parsed_body = None

    async def load_body(self):
        if self._parsed_body is None:
            try:
                self._parsed_body = await self.request.json()
            except Exception:
                self._parsed_body = {}
        return self._parsed_body

    def _send(self, status, payload=None):
        if status == 204:
            response = Response(status_code=204)
        else:
            response = JSONResponse(status_code=status, content=payload)
        telemetry.count(f"http_{status}")
        operation = self._operation()
        if operation:
            telemetry.count(
                f"{operation}.{'error' if status >= 400 else 'ok'}"
            )
        return response

    def _operation(self):
        path = self.request.url.path.rstrip("/")
        collection = path == BASE_PATH.rstrip("/")
        verb = {"POST": "store", "PUT": "store", "PATCH": "update", "DELETE": "delete"}.get(
            self.request.method, "list" if collection else "read"
        )
        return f"{ENTITY}.{verb}" if ENTITY else ""

    def _body(self) -> dict:
        return self._parsed_body if self._parsed_body is not None else {}

    def _query(self) -> dict:
        """Query-string fields for GET/HEAD — not a JSON body."""
        return {key: value for key, value in self.request.query_params.multi_items()}

    def _malformed(self):
        body = self._body()
        if not isinstance(body, dict):
            return {"error": "the body must be a JSON object"}
        missing = [name for name in REQUIRED_FIELDS if name not in body]
        if missing:
            return {
                "error": "missing required field(s): " + ", ".join(missing),
                "fields": missing,
            }
        for name, kind in FIELD_TYPES.items():
            if name not in body:
                continue
            value = body[name]
            if kind == "integer":
                if isinstance(value, bool):
                    return {"error": f"{name} must be a whole number"}
                if AMOUNT_ROUNDING:
                    if not isinstance(value, (int, float)):
                        return {"error": f"{name} must be a whole number"}
                elif not isinstance(value, int):
                    return {"error": f"{name} must be a whole number"}
            if kind == "date-time":
                from datetime import datetime
                try:
                    datetime.fromisoformat(str(value))
                except ValueError:
                    return {"error": f"{name} must be an ISO 8601 date-time"}
        if AMOUNT_ROUNDING:
            from decimal import ROUND_HALF_EVEN, ROUND_HALF_UP, Decimal
            mode = ROUND_HALF_UP if AMOUNT_ROUNDING == "half_up" else ROUND_HALF_EVEN
            for name, kind in FIELD_TYPES.items():
                if kind != "integer" or name not in body:
                    continue
                value = body[name]
                if isinstance(value, float):
                    body[name] = int(
                        (Decimal(str(value)) * 100).to_integral_value(rounding=mode)
                    )
        for ref in REFERENCES:
            field = ref.get("field")
            service = ref.get("service")
            if not field or not service or field not in body:
                continue
            if open_store(service).get(str(body[field])) is None:
                return {
                    "error": (
                        f"{field} names a {ref.get('resource', 'record')} "
                        f"that was never stored"
                    ),
                    "fields": [field],
                }
        return None

    def _caller(self) -> str:
        if not '':
            return ""
        raw = self.request.headers.get('', "")
        if AUTH_SCHEME == "bearer":
            if not raw.lower().startswith("bearer "):
                return ""
            token = raw[7:].strip()
            return token if token else ""
        return raw

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        return self._send(
            200,
            {
                "service": SERVICE_NAME,
                "version": SERVICE_VERSION,
                "counters": dict(telemetry.snapshot(), **store_counters),
            },
        )

    def create(self):
        """Exchange a single-use authorization code for an access token."""
        result = exchange_code(self._body())
        if result is None:
            return self._send(400, {"error": "invalid_grant"})
        return self._send(200, result)


def _mismatch(presented, stored):
    """A mismatch when both sides are present and differ; otherwise none."""
    if presented is None or stored is None:
        return False
    return presented != stored


# A single lock over the whole check-and-write. It closes the read-before-write
# window: two concurrent requests for the same code cannot both pass the
# unexchanged check and both write, which would lose one client's token. The
# store's own `exchanged` flag is what rejects every later attempt — reused
# codes are refused even after this process restarts. This endpoint is not a
# latency-critical hot path, so serializing the exchange is the simple correct
# choice rather than per-code locks.
_claim_lock = threading.Lock()


def exchange_code(body):
    """Return the token response for a claimable code, or None if not valid.

    A single authorization code is spent exactly once: it must exist, be
    unexpired (R-1235.143), and never have been exchanged already. Expired,
    unknown, and reused codes all fail the same way — a generic invalid_grant —
    so an attacker cannot tell which failure they hit.
    """
    if not isinstance(body, dict):
        return None

    grant_type = body.get("grant_type")
    code = body.get("code")
    if not grant_type or not code:
        return None

    now = clock.now()
    with _claim_lock:
        record = store.get(str(code))
        if record is None:
            return None
        issued_at = float(record.get("issued_at", 0.0))
        if now - issued_at > CODE_LIFETIME_SECONDS:
            return None
        if record.get("exchanged"):
            return None

        client_id = body.get("client_id")
        stored_client_id = record.get("client_id")
        redirect_uri = body.get("redirect_uri")
        stored_redirect_uri = record.get("redirect_uri")
        if _mismatch(client_id, stored_client_id):
            return None
        if _mismatch(redirect_uri, stored_redirect_uri):
            return None

        claimed = dict(record)
        claimed["exchanged"] = True
        claimed["issued_at"] = issued_at
        claimed["access_token"] = uuid.uuid4().hex
        claimed["token_type"] = TOKEN_TYPE
        claimed["scope"] = record.get("scope", "") or ""
        store.put(claimed, owner=record.get("owner", ""))

        return {
            "access_token": claimed["access_token"],
            "token_type": claimed["token_type"],
            "scope": claimed["scope"],
        }


router = APIRouter()


async def _run(handler, call):
    try:
        return call(handler)
    except StoreUnavailable as error:
        return handler._send(503, {"error": str(error)})
    except Exception as error:  # noqa: BLE001
        return handler._send(500, {"error": str(error)})


@router.get("/health")
async def _route_health(request: Request):
    handler = Handler(request)
    return await _run(handler, lambda h: h.health())

@router.post(BASE_PATH)
async def _route_create(request: Request):
    handler = Handler(request)
    await handler.load_body()
    problem = handler._malformed()
    if problem is not None:
        return handler._send(400, problem)
    return await _run(handler, lambda h: h.create())

    raise HTTPException(status_code=404, detail={"error": "not found"})


def serve(port):
    """Bind this component for local acceptance. Leave the plumbing alone."""
    import uvicorn
    from fastapi import FastAPI

    app = FastAPI()
    app.include_router(router)
    uvicorn.run(app, host="127.0.0.1", port=port, log_level="error")


if __name__ == "__main__":
    serve(8080)
