"""What is switched on (docs/09 D-26).

Generated by The Factory. `flags.json` is the state and is written by a release,
not by hand: every change to it arrives as a commit carrying the work item that
caused it, so "when did this turn on" has an answer in the repository's history.

A merged component is dark until an engineer accepts it and promotes its flag.
Dark means the route answers 404 — the endpoint does not exist as far as any
caller can tell — rather than existing and misbehaving.

`FACTORY_FLAGS_ALL=1` forces every flag on. The check suite sets it, because it
is testing the code and not the rollout; nothing else should.
"""

import json
import os
import pathlib
import threading

STATE = pathlib.Path(os.environ.get("FACTORY_FLAGS_FILE") or
                     (pathlib.Path(__file__).resolve().parent / "flags.json"))

_lock = threading.Lock()
_cache = {"mtime": None, "flags": {}}


def _load():
    """Re-read the state when the file changes, so a release takes effect."""
    try:
        mtime = STATE.stat().st_mtime
    except OSError:
        return {}
    with _lock:
        if _cache["mtime"] != mtime:
            try:
                loaded = json.loads(STATE.read_text())
            except (OSError, ValueError):
                loaded = {}
            _cache["flags"] = loaded.get("flags", loaded) if isinstance(loaded, dict) else {}
            _cache["mtime"] = mtime
        return dict(_cache["flags"])


def on(name):
    """Whether this flag is switched on. Unknown flags are off."""
    if os.environ.get("FACTORY_FLAGS_ALL") == "1":
        return True
    return bool(_load().get(name))


def all_on():
    """Every flag currently on, for the health endpoint."""
    if os.environ.get("FACTORY_FLAGS_ALL") == "1":
        return ["*"]
    return sorted(name for name, value in _load().items() if value)
