"""the system shall store a forum with a title and optional description and return the forum by id.

Generated by The Factory from its requirement graph.
"""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse, Response

import secrets
import telemetry
from store import StoreUnavailable, open_store
from store import counters as store_counters

SERVICE_NAME = 'forums'
SERVICE_VERSION = "1.0.0"
ENTITY = 'forum'
BASE_PATH = '/forums'
RETENTION_DAYS = None
RECORD_FIELDS = ['title', 'description', 'thread']
STORE_ATTEMPTS = 1
IDENTITY_FIELD = None
UNIQUE_FIELDS = []
REQUIRED_FIELDS = []
FIELD_TYPES = {}
AMOUNT_ROUNDING = None
REFERENCES = []
AUTH_SCHEME = 'plain'
IDEMPOTENCY_HEADER = 'Idempotency-Key'
OWNER_HEADER = 'X-Owner-Id'

store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS)
_IDEMPOTENCY_KEYS = {}


class Handler:
    """Contract plumbing and behaviour handlers. Complete the TODO methods only."""

    def __init__(self, request: Request):
        self.request = request
        self._parsed_body = None

    async def load_body(self):
        if self._parsed_body is None:
            try:
                self._parsed_body = await self.request.json()
            except Exception:
                self._parsed_body = {}
        return self._parsed_body

    def _send(self, status, payload=None):
        if status == 204:
            response = Response(status_code=204)
        else:
            response = JSONResponse(status_code=status, content=payload)
        telemetry.count(f"http_{status}")
        operation = self._operation()
        if operation:
            telemetry.count(
                f"{operation}.{'error' if status >= 400 else 'ok'}"
            )
        return response

    def _operation(self):
        path = self.request.url.path.rstrip("/")
        collection = path == BASE_PATH.rstrip("/")
        verb = {"POST": "store", "PUT": "store", "PATCH": "update", "DELETE": "delete"}.get(
            self.request.method, "list" if collection else "read"
        )
        return f"{ENTITY}.{verb}" if ENTITY else ""

    def _body(self) -> dict:
        return self._parsed_body if self._parsed_body is not None else {}

    def _query(self) -> dict:
        """Query-string fields for GET/HEAD — not a JSON body."""
        return {key: value for key, value in self.request.query_params.multi_items()}

    def _malformed(self):
        body = self._body()
        if not isinstance(body, dict):
            return {"error": "the body must be a JSON object"}
        missing = [name for name in REQUIRED_FIELDS if name not in body]
        if missing:
            return {
                "error": "missing required field(s): " + ", ".join(missing),
                "fields": missing,
            }
        for name, kind in FIELD_TYPES.items():
            if name not in body:
                continue
            value = body[name]
            if kind == "integer":
                if isinstance(value, bool):
                    return {"error": f"{name} must be a whole number"}
                if AMOUNT_ROUNDING:
                    if not isinstance(value, (int, float)):
                        return {"error": f"{name} must be a whole number"}
                elif not isinstance(value, int):
                    return {"error": f"{name} must be a whole number"}
            if kind == "date-time":
                from datetime import datetime
                try:
                    datetime.fromisoformat(str(value))
                except ValueError:
                    return {"error": f"{name} must be an ISO 8601 date-time"}
        if AMOUNT_ROUNDING:
            from decimal import ROUND_HALF_EVEN, ROUND_HALF_UP, Decimal
            mode = ROUND_HALF_UP if AMOUNT_ROUNDING == "half_up" else ROUND_HALF_EVEN
            for name, kind in FIELD_TYPES.items():
                if kind != "integer" or name not in body:
                    continue
                value = body[name]
                if isinstance(value, float):
                    body[name] = int(
                        (Decimal(str(value)) * 100).to_integral_value(rounding=mode)
                    )
        for ref in REFERENCES:
            field = ref.get("field")
            service = ref.get("service")
            if not field or not service or field not in body:
                continue
            if open_store(service).get(str(body[field])) is None:
                return {
                    "error": (
                        f"{field} names a {ref.get('resource', 'record')} "
                        f"that was never stored"
                    ),
                    "fields": [field],
                }
        return None

    def _caller(self) -> str:
        if not 'X-Owner-Id':
            return ""
        raw = self.request.headers.get('X-Owner-Id', "")
        if AUTH_SCHEME == "bearer":
            if not raw.lower().startswith("bearer "):
                return ""
            token = raw[7:].strip()
            return token if token else ""
        return raw

    def _idempotency_key(self) -> str:
        """Idempotency-Key from the request header when the contract requires it.

        Criteria and the Try-it pack send the header. Do not read a body field
        named ``idempotency_key`` — that is not the contract surface.
        """
        if not IDEMPOTENCY_HEADER:
            return ""
        return (self.request.headers.get(IDEMPOTENCY_HEADER) or "").strip()

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        return self._send(
            200,
            {
                "service": SERVICE_NAME,
                "version": SERVICE_VERSION,
                "counters": dict(telemetry.snapshot(), **store_counters),
            },
        )

    def create(self):
        """Store the body as it was sent and answer 201 with the record.

        Store every field the caller sent, unchanged, with
        `store.put(record, owner)` — which fills in "id" and "owner" and
        returns what was stored, which is exactly what the contract's 201
        response describes. Require no particular field: the contract names none, so a
        component that insists on one refuses requests the criteria expect it
        to accept. Refuse only a body that is not an object.

        When IDEMPOTENCY_HEADER is set, a repeated Idempotency-Key replays the
        prior 201 body so the effect happens once and both calls agree.

        When the item route is keyed by IDENTITY_FIELD (e.g. client_id), the
        201 body always carries that field — either the caller's value or the
        store id —         so GET /…/{param} and criteria that read it back agree.
        A missing client_secret (when the contract projects one) is minted once.
        """
        problem = self._malformed()
        if problem is not None:
            return self._send(400, problem)
        body = self._body()
        if not isinstance(body, dict):
            return self._send(400, {"error": "the body must be a JSON object"})
        key = self._idempotency_key() if IDEMPOTENCY_HEADER else ""
        if key and key in _IDEMPOTENCY_KEYS:
            return self._send(201, _IDEMPOTENCY_KEYS[key])
        record = dict(body)
        # Item routes named /{client_id} (etc.) use that field as the store id,
        # so GET /…/{client_id} finds what POST just wrote.
        if IDENTITY_FIELD and record.get(IDENTITY_FIELD) and not record.get("id"):
            record["id"] = str(record[IDENTITY_FIELD])
        for field in UNIQUE_FIELDS or ():
            value = record.get(field)
            if value is None or value == "":
                continue
            for existing in store.list() or []:
                if str(existing.get(field) or "") != str(value):
                    continue
                if str(existing.get("id") or "") == str(record.get("id") or ""):
                    continue
                return self._send(409, {"error": "conflict", "field": field})
        if (
            "client_secret" in RECORD_FIELDS
            and not record.get("client_secret")
        ):
            record["client_secret"] = secrets.token_urlsafe(24)
        stored = store.put(record, owner=self._caller() or "")
        if IDENTITY_FIELD and not stored.get(IDENTITY_FIELD):
            stored = dict(stored)
            stored[IDENTITY_FIELD] = stored.get("id")
            stored = store.put(stored, owner=self._caller() or "")
        if key:
            _IDEMPOTENCY_KEYS[key] = stored
        return self._send(201, stored)

    def fetch(self, record_id):
        """Answer 200 with the record, 404 when there is none, and 403 when the caller is not the record's owner.

        `store.get(record_id)` returns the record or None;
        `store.owner_of(record_id)` returns who stored it.
        """
        record = store.get(record_id)
        if record is None:
            return self._send(404, {"error": "not found"})
        owner = store.owner_of(record_id)
        caller = self._caller()
        if caller and owner and owner != caller:
            return self._send(403, {"error": "forbidden"})
        return self._send(200, record)

    def post_threads(self, forum_id):
        """Store a thread under this forum.

        Path param `forum_id` must name an existing forum; otherwise 404. The body is stored
        in the `threads` store with `forum_id` set
        from the path. Idempotency-Key (when configured) replays
        the prior 201 so retries do not duplicate.
        """
        problem = self._malformed()
        if problem is not None:
            return self._send(400, problem)
        body = self._body()
        if not isinstance(body, dict):
            return self._send(400, {"error": "the body must be a JSON object"})
        parents = open_store(
            'forums', None, [], STORE_ATTEMPTS,
        )
        if parents.get(forum_id) is None:
            return self._send(404, {"error": "not found"})
        children = open_store(
            'threads', RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS,
        )
        key = self._idempotency_key() if IDEMPOTENCY_HEADER else ""
        if key and key in _IDEMPOTENCY_KEYS:
            return self._send(201, _IDEMPOTENCY_KEYS[key])
        record = dict(body)
        record['forum_id'] = forum_id
        stored = children.put(record, owner=self._caller() or "")
        if key:
            _IDEMPOTENCY_KEYS[key] = stored
        return self._send(201, stored)

    def get_threads(self, forum_id, id):
        """Return a thread in this forum.

        404 when the id was never stored under `forum_id`;
        403 when the caller is not the record's owner and auth is
        required.
        """
        children = open_store(
            'threads', RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS,
        )
        record = children.get(id)
        if record is None:
            return self._send(404, {"error": "not found"})
        if str(record.get('forum_id') or "") != str(forum_id):
            return self._send(404, {"error": "not found"})
        owner = children.owner_of(id) or ""
        caller = self._caller()
        if caller and owner and owner != caller:
            return self._send(403, {"error": "forbidden"})
        return self._send(200, record)



router = APIRouter()


async def _run(handler, call):
    try:
        return call(handler)
    except StoreUnavailable as error:
        return handler._send(503, {"error": str(error)})
    except Exception as error:  # noqa: BLE001
        return handler._send(500, {"error": str(error)})


@router.get("/health")
async def _route_health(request: Request):
    handler = Handler(request)
    return await _run(handler, lambda h: h.health())

@router.post(BASE_PATH)
async def _route_create(request: Request):
    handler = Handler(request)
    if not handler._caller():
        return handler._send(401, {"error": "an owner is required"})
    await handler.load_body()
    problem = handler._malformed()
    if problem is not None:
        return handler._send(400, problem)
    return await _run(handler, lambda h: h.create())

@router.get(BASE_PATH + "/{record_id}")
async def _route_fetch(request: Request, record_id: str):
    handler = Handler(request)
    if not handler._caller():
        return handler._send(401, {"error": "an owner is required"})
    handler._parsed_body = {'id': record_id}
    return await _run(handler, lambda h: h.fetch(record_id))

@router.post('/forums/{forum_id}/threads')
async def _route_post_threads(request: Request, forum_id: str):
    handler = Handler(request)
    if not handler._caller():
        return handler._send(401, {"error": "an owner is required"})
    await handler.load_body()
    return await _run(handler, lambda h: h.post_threads(forum_id))

@router.get('/forums/{forum_id}/threads/{id}')
async def _route_get_threads(request: Request, forum_id: str, id: str):
    handler = Handler(request)
    if not handler._caller():
        return handler._send(401, {"error": "an owner is required"})
    return await _run(handler, lambda h: h.get_threads(forum_id, id))

    raise HTTPException(status_code=404, detail={"error": "not found"})


def serve(port):
    """Bind this component for local acceptance. Leave the plumbing alone."""
    import uvicorn
    from fastapi import FastAPI

    app = FastAPI()
    app.include_router(router)
    uvicorn.run(app, host="127.0.0.1", port=port, log_level="error")


if __name__ == "__main__":
    serve(8080)
