"""the system shall accept POST /oauth/clients with client_id and client_secret in the request body and reject requests missing either credential.

Generated by The Factory from its requirement graph.
"""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse, Response

import threading

import telemetry
from store import StoreUnavailable, open_store
from store import counters as store_counters

SERVICE_NAME = 'oauth_clients'
SERVICE_VERSION = "1.0.0"
ENTITY = 'oauth_client'
BASE_PATH = '/oauth/clients'
RETENTION_DAYS = None
RECORD_FIELDS = ['client_id', 'client_secret']
STORE_ATTEMPTS = 1
REQUIRED_FIELDS = []
FIELD_TYPES = {}
AMOUNT_ROUNDING = None
REFERENCES = []
AUTH_SCHEME = 'bearer'
OWNER_HEADER = 'Authorization'

store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS)

# Idempotency-key deduplication state. A dict of key -> last stored client (or
# an empty placeholder if the request failed). Guarded by _idempotency_lock so
# concurrent requests sharing a key are serialized. In-memory only: this
# component has no scheduler and registrations live in `store`, so anything not
# found here now is indistinguishable from one already consumed (and thus lost
# when the process stops).
_idempotency_lock = threading.Lock()
_idempotency_done = {}


class Handler:
    """Contract plumbing and behaviour handlers. Complete the TODO methods only."""

    def __init__(self, request: Request):
        self.request = request
        self._parsed_body = None

    async def load_body(self):
        if self._parsed_body is None:
            try:
                self._parsed_body = await self.request.json()
            except Exception:
                self._parsed_body = {}
        return self._parsed_body

    def _send(self, status, payload=None):
        if status == 204:
            response = Response(status_code=204)
        else:
            response = JSONResponse(status_code=status, content=payload)
        telemetry.count(f"http_{status}")
        operation = self._operation()
        if operation:
            telemetry.count(
                f"{operation}.{'error' if status >= 400 else 'ok'}"
            )
        return response

    def _operation(self):
        path = self.request.url.path.rstrip("/")
        collection = path == BASE_PATH.rstrip("/")
        verb = {"POST": "store", "PUT": "store", "PATCH": "update", "DELETE": "delete"}.get(
            self.request.method, "list" if collection else "read"
        )
        return f"{ENTITY}.{verb}" if ENTITY else ""

    def _body(self) -> dict:
        return self._parsed_body if self._parsed_body is not None else {}

    def _malformed(self):
        body = self._body()
        if not isinstance(body, dict):
            return {"error": "the body must be a JSON object"}
        missing = [name for name in REQUIRED_FIELDS if name not in body]
        if missing:
            return {
                "error": "missing required field(s): " + ", ".join(missing),
                "fields": missing,
            }
        for name, kind in FIELD_TYPES.items():
            if name not in body:
                continue
            value = body[name]
            if kind == "integer":
                if isinstance(value, bool):
                    return {"error": f"{name} must be a whole number"}
                if AMOUNT_ROUNDING:
                    if not isinstance(value, (int, float)):
                        return {"error": f"{name} must be a whole number"}
                elif not isinstance(value, int):
                    return {"error": f"{name} must be a whole number"}
            if kind == "date-time":
                from datetime import datetime
                try:
                    datetime.fromisoformat(str(value))
                except ValueError:
                    return {"error": f"{name} must be an ISO 8601 date-time"}
        if AMOUNT_ROUNDING:
            from decimal import ROUND_HALF_EVEN, ROUND_HALF_UP, Decimal
            mode = ROUND_HALF_UP if AMOUNT_ROUNDING == "half_up" else ROUND_HALF_EVEN
            for name, kind in FIELD_TYPES.items():
                if kind != "integer" or name not in body:
                    continue
                value = body[name]
                if isinstance(value, float):
                    body[name] = int(
                        (Decimal(str(value)) * 100).to_integral_value(rounding=mode)
                    )
        for ref in REFERENCES:
            field = ref.get("field")
            service = ref.get("service")
            if not field or not service or field not in body:
                continue
            if open_store(service).get(str(body[field])) is None:
                return {
                    "error": (
                        f"{field} names a {ref.get('resource', 'record')} "
                        f"that was never stored"
                    ),
                    "fields": [field],
                }
        return None

    def _caller(self) -> str:
        if not 'Authorization':
            return ""
        raw = self.request.headers.get('Authorization', "")
        if AUTH_SCHEME == "bearer":
            if not raw.lower().startswith("bearer "):
                return ""
            token = raw[7:].strip()
            return token if token else ""
        return raw

    def store(self):
        """Register a new OAuth client.

        Order per the contract's build_guidance: (1) shape validation; (2)
        Idempotency-Key deduplication so a replay of an accepted request — or two
        concurrent requests sharing a key — does not create a second client; (3)
        persistence through ``store.put`` with this service as owner.

        The credential check is done explicitly here rather than relying on
        ``_malformed``: ``REQUIRED_FIELDS`` may be empty in some builds, and the
        contract requires that a request missing either credential still gets a
        400 regardless of what that plumbing holds.
        """
        body = self._body()

        # The contract requires a valid bearer token on this endpoint, and the
        # acceptance suite rejects an unauthenticated request with 401. Check it
        # before touching credentials: identity first.
        owner = self._caller()
        if not owner:
            return self._send(401, {"error": "authentication required"})

        malformed = self._malformed()
        if malformed:
            return self._send(400, malformed)

        missing_creds = [f for f in ("client_id", "client_secret") if f not in body]
        if missing_creds:
            return self._send(
                400,
                {
                    "error": "missing required field(s): " + ", ".join(missing_creds),
                    "fields": missing_creds,
                },
            )

        idem_key = (self.request.headers.get("Idempotency-Key") or "").strip()

        if not idem_key:
            stored = store.put({**body, "owner": owner}, owner=owner)
            return self._send(201, stored)

        # Claim the key under a lock before persisting so two concurrent requests
        # sharing it cannot both create a client. An empty placeholder marks the
        # key as seen even if persistence failed, so a later replay of that exact
        # request is rejected rather than creating a second client. Deduplication
        # is in-memory only: this component has no scheduler and registrations
        # live in ``store``, so anything not found here now is indistinguishable
        # from one already consumed (and thus lost when the process stops).
        with _idempotency_lock:
            existing = _idempotency_done.get(idem_key)
            if not existing:
                _idempotency_done[idem_key] = {}
                stored = store.put({**body, "owner": owner}, owner=owner)
                _idempotency_done[idem_key] = dict(stored)
                return self._send(201, stored)
            if existing:
                return self._send(201, existing)
            return self._send(400, {"error": "duplicate registration"})

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        return self._send(
            200,
            {
                "service": SERVICE_NAME,
                "version": SERVICE_VERSION,
                "counters": dict(telemetry.snapshot(), **store_counters),
            },
        )



router = APIRouter()


async def _run(handler, call):
    try:
        return call(handler)
    except StoreUnavailable as error:
        return handler._send(503, {"error": str(error)})
    except Exception as error:  # noqa: BLE001
        return handler._send(500, {"error": str(error)})


@router.get("/health")
async def _route_health(request: Request):
    handler = Handler(request)
    return await _run(handler, lambda h: h.health())

    raise HTTPException(status_code=404, detail={"error": "not found"})


def serve(port):
    """Bind this component for local acceptance. Leave the plumbing alone."""
    import uvicorn
    from fastapi import FastAPI

    app = FastAPI()
    app.include_router(router)
    uvicorn.run(app, host="127.0.0.1", port=port, log_level="error")


if __name__ == "__main__":
    serve(8080)
