"""the system shall issue a single-use authorization code valid for 10 minutes, return it via redirect to the client's registered redirect_uri, bind the approved scopes to the code, and reject expired, reused, or scope-mismatched redemption attempts with HTTP 400 Invalid Grant.

Generated by The Factory from its requirement graph.
"""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse, Response

import telemetry
from store import StoreUnavailable, open_store
from store import counters as store_counters
from fastapi.responses import RedirectResponse
import secrets
from store import clock

SERVICE_NAME = 'oauth'
SERVICE_VERSION = "1.0.0"
ENTITY = 'oauth'
BASE_PATH = '/oauth'
RETENTION_DAYS = None
RECORD_FIELDS = ['redirect_uri', 'scopes']
STORE_ATTEMPTS = 1
REQUIRED_FIELDS = []
FIELD_TYPES = {}
AMOUNT_ROUNDING = None
REFERENCES = []
AUTH_SCHEME = 'plain'
OWNER_HEADER = 'Authorization'

store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS)


class Handler:
    """Contract plumbing and behaviour handlers. Complete the TODO methods only."""

    def __init__(self, request: Request):
        self.request = request
        self._parsed_body = None

    async def load_body(self):
        if self._parsed_body is None:
            try:
                self._parsed_body = await self.request.json()
            except Exception:
                self._parsed_body = {}
        return self._parsed_body

    def _send(self, status, payload=None):
        if status == 204:
            response = Response(status_code=204)
        else:
            response = JSONResponse(status_code=status, content=payload)
        telemetry.count(f"http_{status}")
        operation = self._operation()
        if operation:
            telemetry.count(
                f"{operation}.{'error' if status >= 400 else 'ok'}"
            )
        return response

    def _operation(self):
        path = self.request.url.path.rstrip("/")
        collection = path == BASE_PATH.rstrip("/")
        verb = {"POST": "store", "PUT": "store", "PATCH": "update", "DELETE": "delete"}.get(
            self.request.method, "list" if collection else "read"
        )
        return f"{ENTITY}.{verb}" if ENTITY else ""

    def _body(self) -> dict:
        return self._parsed_body if self._parsed_body is not None else {}

    def _query(self) -> dict:
        """Query-string fields for GET/HEAD — not a JSON body."""
        return {key: value for key, value in self.request.query_params.multi_items()}

    def _malformed(self):
        body = self._body()
        if not isinstance(body, dict):
            return {"error": "the body must be a JSON object"}
        missing = [name for name in REQUIRED_FIELDS if name not in body]
        if missing:
            return {
                "error": "missing required field(s): " + ", ".join(missing),
                "fields": missing,
            }
        for name, kind in FIELD_TYPES.items():
            if name not in body:
                continue
            value = body[name]
            if kind == "integer":
                if isinstance(value, bool):
                    return {"error": f"{name} must be a whole number"}
                if AMOUNT_ROUNDING:
                    if not isinstance(value, (int, float)):
                        return {"error": f"{name} must be a whole number"}
                elif not isinstance(value, int):
                    return {"error": f"{name} must be a whole number"}
            if kind == "date-time":
                from datetime import datetime
                try:
                    datetime.fromisoformat(str(value))
                except ValueError:
                    return {"error": f"{name} must be an ISO 8601 date-time"}
        if AMOUNT_ROUNDING:
            from decimal import ROUND_HALF_EVEN, ROUND_HALF_UP, Decimal
            mode = ROUND_HALF_UP if AMOUNT_ROUNDING == "half_up" else ROUND_HALF_EVEN
            for name, kind in FIELD_TYPES.items():
                if kind != "integer" or name not in body:
                    continue
                value = body[name]
                if isinstance(value, float):
                    body[name] = int(
                        (Decimal(str(value)) * 100).to_integral_value(rounding=mode)
                    )
        for ref in REFERENCES:
            field = ref.get("field")
            service = ref.get("service")
            if not field or not service or field not in body:
                continue
            if open_store(service).get(str(body[field])) is None:
                return {
                    "error": (
                        f"{field} names a {ref.get('resource', 'record')} "
                        f"that was never stored"
                    ),
                    "fields": [field],
                }
        return None

    def _caller(self) -> str:
        if not 'Authorization':
            return ""
        raw = self.request.headers.get('Authorization', "")
        if AUTH_SCHEME == "bearer":
            if not raw.lower().startswith("bearer "):
                return ""
            token = raw[7:].strip()
            return token if token else ""
        return raw

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        return self._send(
            200,
            {
                "service": SERVICE_NAME,
                "version": SERVICE_VERSION,
                "counters": dict(telemetry.snapshot(), **store_counters),
            },
        )

    def get_authorize(self):
        """GET /oauth/authorize — issue a single-use code via redirect."""
        # POST alias may have loaded a body; only refuse when a body was parsed
        # and is not an object. GET leaves _parsed_body unset.
        if self._parsed_body is not None and not isinstance(self._parsed_body, dict):
            return self._send(400, {"error": "the body must be a JSON object"})

        q = self._query()
        client_id = q.get("client_id") or ""
        redirect_uri = q.get("redirect_uri") or ""
        response_type = q.get("response_type") or ""
        scope = q.get("scope") or ""
        state = q.get("state")
        if not isinstance(client_id, str) or not client_id:
            return self._send(400, {"error": "client_id is required"})
        if not isinstance(redirect_uri, str) or not redirect_uri:
            return self._send(400, {"error": "redirect_uri is required"})
        if response_type != "code":
            return self._send(400, {"error": "unsupported response_type; expected 'code'"})
        code = generate_authcode()
        now = clock.now()
        bound = [s for s in str(scope).split() if s]
        _issued[code] = {
            "client_id": client_id,
            "registered_redirect_uri": redirect_uri,
            "bound_scopes": bound,
            "redirect_uri": redirect_uri,
            "issued_at": float(now),
        }
        location = f"{redirect_uri}?code={code}"
        if state:
            location += "&state=" + str(state)
        telemetry.count("authorize.issuance")
        return RedirectResponse(status_code=302, url=location)

    def post_token(self):
        """POST /oauth/token — exchange a code for tokens; refuse invalid grants."""
        body = self._body()
        if not isinstance(body, dict):
            return self._send(400, {"error": "the body must be a JSON object"})

        client_id = body.get("client_id")
        code = body.get("code")
        grant_type = body.get("grant_type")
        redirect_uri = body.get("redirect_uri")

        if not isinstance(client_id, str) or not client_id:
            return self._send(400, {"error": "client_id is required"})
        if grant_type != "authorization_code":
            return self._send(400, {"error": "unsupported grant_type; expected 'authorization_code'"})
        if not isinstance(code, str) or not code:
            return self._send(400, {"error": "code is required"})

        info = _issued.get(code)
        if not info:
            telemetry.count("token.rejected")
            return self._send(400, {"error": "invalid_grant"})
        if info.get("client_id") != client_id:
            return self._send(400, {"error": "invalid_grant"})
        if is_code_expired(info["issued_at"], clock.now()):
            telemetry.count("token.expired")
            return self._send(400, {"error": "invalid_grant"})
        if redirect_uri and info["registered_redirect_uri"] != redirect_uri:
            return self._send(400, {"error": "invalid_grant"})

        body = self._body()
        requested_scopes = [s for s in (body.get("scope") or "").split() if s]
        if not validate_scope_match(requested_scopes, info["bound_scopes"]):
            telemetry.count("token.scope_mismatch")
            return self._send(400, {"error": "invalid_scope"})

        mark_code_redeemed(code)
        access_token = secrets.token_hex(32)
        telemetry.count("token.exchange")
        return self._send(200, {
            "access_token": access_token,
            "token_type": "Bearer",
            "expires_in": TOKEN_EXPIRES_IN,
        })



router = APIRouter()


async def _run(handler, call):
    try:
        return call(handler)
    except StoreUnavailable as error:
        return handler._send(503, {"error": str(error)})
    except Exception as error:  # noqa: BLE001
        return handler._send(500, {"error": str(error)})


@router.get("/health")
async def _route_health(request: Request):
    handler = Handler(request)
    return await _run(handler, lambda h: h.health())

@router.get('/oauth/authorize')
async def _route_get_authorize(request: Request):
    handler = Handler(request)
    return await _run(handler, lambda h: h.get_authorize())

@router.post('/authorize')
async def _route_post_authorize(request: Request):
    """POST /authorize alias — refuse a non-object body with 400, then issue."""
    handler = Handler(request)
    return await _run(handler, lambda h: h.post_token())

@router.post('/oauth/token')
async def _route_post_token(request: Request):
    handler = Handler(request)
    if not handler._caller():
        return handler._send(401, {"error": "an owner is required"})
    await handler.load_body()
    return await _run(handler, lambda h: h.post_token())

    raise HTTPException(status_code=404, detail={"error": "not found"})


def serve(port):
    """Bind this component for local acceptance. Leave the plumbing alone."""
    import uvicorn
    from fastapi import FastAPI

    app = FastAPI()
    app.include_router(router)
    uvicorn.run(app, host="127.0.0.1", port=port, log_level="error")


if __name__ == "__main__":
    serve(8080)

def generate_authcode() -> str:
    """Produce a cryptographically secure single-use code string."""
    return secrets.token_urlsafe(32)

def _client_redirect_uri(client_id):
    record = store.get(client_id)
    if not record:
        return None
    value = record.get('redirect_uri')
    return value if isinstance(value, str) else None

def is_code_expired(issued_at, now=None) -> bool:
    """True when a code's 10-minute validity window has passed."""
    if now is None:
        now = clock.now()
    start = float(issued_at.timestamp() if hasattr(issued_at, 'timestamp') else issued_at)
    return (float(now) - start) > AUTH_CODE_TTL_SECONDS

def validate_scope_match(requested_scopes, bound_scopes) -> bool:
    """True when the requested scopes are covered by those bound to the code."""
    if not isinstance(bound_scopes, list):
        return False
    for scope in requested_scopes or []:
        if scope not in bound_scopes:
            return False
    return True

def mark_code_redeemed(code) -> None:
    """Record single-use redemption; the first use consumes the code."""
    _issued.pop(code, None)

AUTH_CODE_TTL_SECONDS = 600

TOKEN_EXPIRES_IN = 3600

_issued = {}
