"""the system shall expose GET /oauth/authorize that issues an authorization code when client_id exists in oauth_clients and redirect_uri matches that client; refuse unknown client_id or non-matching redirect_uri with HTTP 400 including an error field Currently: get_authorize was NotImplementedError; oauth_clients sibling schema missing in isolation.

Generated by The Factory from its requirement graph.
"""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse, Response

import secrets
import telemetry
from store import StoreUnavailable, open_store
from store import counters as store_counters

SERVICE_NAME = 'oauth'
SERVICE_VERSION = "1.0.0"
ENTITY = 'oauth'
BASE_PATH = '/oauth'
RETENTION_DAYS = None
RECORD_FIELDS = []
STORE_ATTEMPTS = 1
IDENTITY_FIELD = None
REQUIRED_FIELDS = []
FIELD_TYPES = {}
AMOUNT_ROUNDING = None
REFERENCES = []
AUTH_SCHEME = 'plain'
IDEMPOTENCY_HEADER = ''

store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS)
_IDEMPOTENCY_KEYS = {}


class Handler:
    """Contract plumbing and behaviour handlers. Complete the TODO methods only."""

    def __init__(self, request: Request):
        self.request = request
        self._parsed_body = None

    async def load_body(self):
        if self._parsed_body is None:
            try:
                self._parsed_body = await self.request.json()
            except Exception:
                self._parsed_body = {}
        return self._parsed_body

    def _send(self, status, payload=None):
        if status == 204:
            response = Response(status_code=204)
        else:
            response = JSONResponse(status_code=status, content=payload)
        telemetry.count(f"http_{status}")
        operation = self._operation()
        if operation:
            telemetry.count(
                f"{operation}.{'error' if status >= 400 else 'ok'}"
            )
        return response

    def _operation(self):
        path = self.request.url.path.rstrip("/")
        collection = path == BASE_PATH.rstrip("/")
        verb = {"POST": "store", "PUT": "store", "PATCH": "update", "DELETE": "delete"}.get(
            self.request.method, "list" if collection else "read"
        )
        return f"{ENTITY}.{verb}" if ENTITY else ""

    def _body(self) -> dict:
        return self._parsed_body if self._parsed_body is not None else {}

    def _query(self) -> dict:
        """Query-string fields for GET/HEAD — not a JSON body."""
        return {key: value for key, value in self.request.query_params.multi_items()}

    def _malformed(self):
        body = self._body()
        if not isinstance(body, dict):
            return {"error": "the body must be a JSON object"}
        missing = [name for name in REQUIRED_FIELDS if name not in body]
        if missing:
            return {
                "error": "missing required field(s): " + ", ".join(missing),
                "fields": missing,
            }
        for name, kind in FIELD_TYPES.items():
            if name not in body:
                continue
            value = body[name]
            if kind == "integer":
                if isinstance(value, bool):
                    return {"error": f"{name} must be a whole number"}
                if AMOUNT_ROUNDING:
                    if not isinstance(value, (int, float)):
                        return {"error": f"{name} must be a whole number"}
                elif not isinstance(value, int):
                    return {"error": f"{name} must be a whole number"}
            if kind == "date-time":
                from datetime import datetime
                try:
                    datetime.fromisoformat(str(value))
                except ValueError:
                    return {"error": f"{name} must be an ISO 8601 date-time"}
        if AMOUNT_ROUNDING:
            from decimal import ROUND_HALF_EVEN, ROUND_HALF_UP, Decimal
            mode = ROUND_HALF_UP if AMOUNT_ROUNDING == "half_up" else ROUND_HALF_EVEN
            for name, kind in FIELD_TYPES.items():
                if kind != "integer" or name not in body:
                    continue
                value = body[name]
                if isinstance(value, float):
                    body[name] = int(
                        (Decimal(str(value)) * 100).to_integral_value(rounding=mode)
                    )
        for ref in REFERENCES:
            field = ref.get("field")
            service = ref.get("service")
            if not field or not service or field not in body:
                continue
            if open_store(service).get(str(body[field])) is None:
                return {
                    "error": (
                        f"{field} names a {ref.get('resource', 'record')} "
                        f"that was never stored"
                    ),
                    "fields": [field],
                }
        return None

    def _caller(self) -> str:
        if not '':
            return ""
        raw = self.request.headers.get('', "")
        if AUTH_SCHEME == "bearer":
            if not raw.lower().startswith("bearer "):
                return ""
            token = raw[7:].strip()
            return token if token else ""
        return raw

    def _idempotency_key(self) -> str:
        """Idempotency-Key from the request header when the contract requires it.

        Criteria and the Try-it pack send the header. Do not read a body field
        named ``idempotency_key`` — that is not the contract surface.
        """
        if not IDEMPOTENCY_HEADER:
            return ""
        return (self.request.headers.get(IDEMPOTENCY_HEADER) or "").strip()

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        return self._send(
            200,
            {
                "service": SERVICE_NAME,
                "version": SERVICE_VERSION,
                "counters": dict(telemetry.snapshot(), **store_counters),
            },
        )

    def post_token(self):
        """Exchange an authorization code for an access token.

        Body fields: grant_type=authorization_code, code, and
        usually redirect_uri / client_id. Unknown, missing, or
        already-used codes answer 400 with an error field. A match
        deletes the one-time code and returns 200 with access_token.
        """
        body = self._body()
        if not isinstance(body, dict):
            body = {}
        grant = str(body.get('grant_type') or '').strip()
        code = str(body.get('code') or '').strip()
        if grant and grant != 'authorization_code':
            return self._send(400, {"error": "unsupported_grant_type"})
        if not code:
            return self._send(400, {"error": "invalid_request"})
        record = store.get(code)
        if record is None:
            for candidate in store.list() or []:
                if str(candidate.get('code') or '') == code:
                    record = candidate
                    break
        if record is None:
            return self._send(400, {"error": "invalid_grant"})
        issued = record.get('issued_at')
        try:
            age = __import__('store').clock.now() - float(issued or 0)
        except (TypeError, ValueError):
            age = 0
        if issued is not None and age > 600:
            store.delete(str(record.get("id") or code))
            return self._send(400, {"error": "invalid_grant"})
        rid = str(record.get('id') or code)
        store.delete(rid)
        token = secrets.token_urlsafe(32)
        return self._send(200, {
            "access_token": token,
            "token_type": "Bearer",
            "expires_in": 3600,
        })



router = APIRouter()


async def _run(handler, call):
    try:
        return call(handler)
    except StoreUnavailable as error:
        return handler._send(503, {"error": str(error)})
    except Exception as error:  # noqa: BLE001
        return handler._send(500, {"error": str(error)})


@router.get("/health")
async def _route_health(request: Request):
    handler = Handler(request)
    return await _run(handler, lambda h: h.health())

@router.post('/oauth/token')
async def _route_post_token(request: Request):
    handler = Handler(request)
    await handler.load_body()
    return await _run(handler, lambda h: h.post_token())

    raise HTTPException(status_code=404, detail={"error": "not found"})


def serve(port):
    """Bind this component for local acceptance. Leave the plumbing alone."""
    import uvicorn
    from fastapi import FastAPI

    app = FastAPI()
    app.include_router(router)
    uvicorn.run(app, host="127.0.0.1", port=port, log_level="error")


if __name__ == "__main__":
    serve(8080)
