"""The system shall expose OAuth client registration at /oauth/clients: an authenticated POST /oauth/clients returns HTTP 201 with JSON fields client_id and client_secret; GET /oauth/clients/{client_id} returns HTTP 200 with that client when the id exists, and HTTP 404 when the id does not exist; requests without auth return HTTP 401 Currently: create/readback/absent-id checks failed; clients component must satisfy POST 201 and GET 200/404 only.

Generated by The Factory from its requirement graph.
"""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse, Response

import secrets
import telemetry
from store import StoreUnavailable, open_store
from store import counters as store_counters

SERVICE_NAME = 'oauth_clients'
SERVICE_VERSION = "1.0.0"
ENTITY = 'oauth_client'
BASE_PATH = '/oauth/clients'
RETENTION_DAYS = None
RECORD_FIELDS = ['client_id', 'client_secret', 'redirect_uris', 'allowed_scopes', 'owner_id', 'created_by', 'description']
STORE_ATTEMPTS = 1
IDENTITY_FIELD = 'client_id'
REQUIRED_FIELDS = []
FIELD_TYPES = {}
AMOUNT_ROUNDING = None
REFERENCES = []
AUTH_SCHEME = 'bearer'
IDEMPOTENCY_HEADER = 'Idempotency-Key'
OWNER_HEADER = 'Authorization'

store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS)
_IDEMPOTENCY_KEYS = {}


class Handler:
    """Contract plumbing and behaviour handlers. Complete the TODO methods only."""

    def __init__(self, request: Request):
        self.request = request
        self._parsed_body = None

    async def load_body(self):
        if self._parsed_body is None:
            try:
                self._parsed_body = await self.request.json()
            except Exception:
                self._parsed_body = {}
        return self._parsed_body

    def _send(self, status, payload=None):
        if status == 204:
            response = Response(status_code=204)
        else:
            response = JSONResponse(status_code=status, content=payload)
        telemetry.count(f"http_{status}")
        operation = self._operation()
        if operation:
            telemetry.count(
                f"{operation}.{'error' if status >= 400 else 'ok'}"
            )
        return response

    def _operation(self):
        path = self.request.url.path.rstrip("/")
        collection = path == BASE_PATH.rstrip("/")
        verb = {"POST": "store", "PUT": "store", "PATCH": "update", "DELETE": "delete"}.get(
            self.request.method, "list" if collection else "read"
        )
        return f"{ENTITY}.{verb}" if ENTITY else ""

    def _body(self) -> dict:
        return self._parsed_body if self._parsed_body is not None else {}

    def _query(self) -> dict:
        """Query-string fields for GET/HEAD — not a JSON body."""
        return {key: value for key, value in self.request.query_params.multi_items()}

    def _malformed(self):
        body = self._body()
        if not isinstance(body, dict):
            return {"error": "the body must be a JSON object"}
        missing = [name for name in REQUIRED_FIELDS if name not in body]
        if missing:
            return {
                "error": "missing required field(s): " + ", ".join(missing),
                "fields": missing,
            }
        for name, kind in FIELD_TYPES.items():
            if name not in body:
                continue
            value = body[name]
            if kind == "integer":
                if isinstance(value, bool):
                    return {"error": f"{name} must be a whole number"}
                if AMOUNT_ROUNDING:
                    if not isinstance(value, (int, float)):
                        return {"error": f"{name} must be a whole number"}
                elif not isinstance(value, int):
                    return {"error": f"{name} must be a whole number"}
            if kind == "date-time":
                from datetime import datetime
                try:
                    datetime.fromisoformat(str(value))
                except ValueError:
                    return {"error": f"{name} must be an ISO 8601 date-time"}
        if AMOUNT_ROUNDING:
            from decimal import ROUND_HALF_EVEN, ROUND_HALF_UP, Decimal
            mode = ROUND_HALF_UP if AMOUNT_ROUNDING == "half_up" else ROUND_HALF_EVEN
            for name, kind in FIELD_TYPES.items():
                if kind != "integer" or name not in body:
                    continue
                value = body[name]
                if isinstance(value, float):
                    body[name] = int(
                        (Decimal(str(value)) * 100).to_integral_value(rounding=mode)
                    )
        for ref in REFERENCES:
            field = ref.get("field")
            service = ref.get("service")
            if not field or not service or field not in body:
                continue
            if open_store(service).get(str(body[field])) is None:
                return {
                    "error": (
                        f"{field} names a {ref.get('resource', 'record')} "
                        f"that was never stored"
                    ),
                    "fields": [field],
                }
        return None

    def _caller(self) -> str:
        if not 'Authorization':
            return ""
        raw = self.request.headers.get('Authorization', "")
        if AUTH_SCHEME == "bearer":
            if not raw.lower().startswith("bearer "):
                return ""
            token = raw[7:].strip()
            return token if token else ""
        return raw

    def _idempotency_key(self) -> str:
        """Idempotency-Key from the request header when the contract requires it.

        Criteria and the Try-it pack send the header. Do not read a body field
        named ``idempotency_key`` — that is not the contract surface.
        """
        if not IDEMPOTENCY_HEADER:
            return ""
        return (self.request.headers.get(IDEMPOTENCY_HEADER) or "").strip()

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        return self._send(
            200,
            {
                "service": SERVICE_NAME,
                "version": SERVICE_VERSION,
                "counters": dict(telemetry.snapshot(), **store_counters),
            },
        )

    def create(self):
        """Store the body as it was sent and answer 201 with the record.

        Store every field the caller sent, unchanged, with
        `store.put(record, owner)` — which fills in "id" and "owner" and
        returns what was stored, which is exactly what the contract's 201
        response describes. Require no particular field: the contract names none, so a
        component that insists on one refuses requests the criteria expect it
        to accept. Refuse only a body that is not an object.

        When IDEMPOTENCY_HEADER is set, a repeated Idempotency-Key replays the
        prior 201 body so the effect happens once and both calls agree.

        When the item route is keyed by IDENTITY_FIELD (e.g. client_id), the
        201 body always carries that field — either the caller's value or the
        store id —         so GET /…/{param} and criteria that read it back agree.
        A missing client_secret (when the contract projects one) is minted once.
        """
        problem = self._malformed()
        if problem is not None:
            return self._send(400, problem)
        body = self._body()
        if not isinstance(body, dict):
            return self._send(400, {"error": "the body must be a JSON object"})
        key = self._idempotency_key() if IDEMPOTENCY_HEADER else ""
        if key and key in _IDEMPOTENCY_KEYS:
            return self._send(201, _IDEMPOTENCY_KEYS[key])
        record = dict(body)
        # Item routes named /{client_id} (etc.) use that field as the store id,
        # so GET /…/{client_id} finds what POST just wrote.
        if IDENTITY_FIELD and record.get(IDENTITY_FIELD) and not record.get("id"):
            record["id"] = str(record[IDENTITY_FIELD])
        if (
            "client_secret" in RECORD_FIELDS
            and not record.get("client_secret")
        ):
            record["client_secret"] = secrets.token_urlsafe(24)
        stored = store.put(record, owner=self._caller() or "")
        if IDENTITY_FIELD and not stored.get(IDENTITY_FIELD):
            stored = dict(stored)
            stored[IDENTITY_FIELD] = stored.get("id")
            stored = store.put(stored, owner=self._caller() or "")
        if key:
            _IDEMPOTENCY_KEYS[key] = stored
        return self._send(201, stored)

    def fetch(self, record_id):
        """Answer 200 with the record, 404 when there is none, and 403 when the caller is not the record's owner.

        `store.get(record_id)` returns the record or None;
        `store.owner_of(record_id)` returns who stored it.
        """
        record = store.get(record_id)
        if record is None:
            return self._send(404, {"error": "not found"})
        owner = store.owner_of(record_id)
        caller = self._caller()
        if caller and owner and owner != caller:
            return self._send(403, {"error": "forbidden"})
        return self._send(200, record)

    def post_rotate_secret(self, client_id):
        """Mint a new client_secret for the record; answer 201.

        Overwrites the prior secret so the old one stops working.
        404 when the id was never stored; 403 when the caller is
        not the record's owner and the contract requires auth.
        """
        record = store.get(client_id)
        if record is None:
            return self._send(404, {"error": "not found"})
        owner = store.owner_of(record.get("id") or client_id) or ""
        if AUTH_SCHEME != "plain" and owner and owner != (self._caller() or ""):
            return self._send(403, {"error": "forbidden"})
        updated = dict(record)
        updated["client_secret"] = secrets.token_urlsafe(24)
        stored = store.put(updated, owner=owner or (self._caller() or ""))
        return self._send(201, stored)



router = APIRouter()


async def _run(handler, call):
    try:
        return call(handler)
    except StoreUnavailable as error:
        return handler._send(503, {"error": str(error)})
    except Exception as error:  # noqa: BLE001
        return handler._send(500, {"error": str(error)})


@router.get("/health")
async def _route_health(request: Request):
    handler = Handler(request)
    return await _run(handler, lambda h: h.health())

@router.post(BASE_PATH)
async def _route_create(request: Request):
    handler = Handler(request)
    if not handler._caller():
        return handler._send(401, {"error": "authentication required"})
    await handler.load_body()
    problem = handler._malformed()
    if problem is not None:
        return handler._send(400, problem)
    return await _run(handler, lambda h: h.create())

@router.get(BASE_PATH + "/{record_id}")
async def _route_fetch(request: Request, record_id: str):
    handler = Handler(request)
    if not handler._caller():
        return handler._send(401, {"error": "authentication required"})
    handler._parsed_body = {'id': record_id}
    return await _run(handler, lambda h: h.fetch(record_id))

@router.post('/oauth/clients/{client_id}/rotate-secret')
async def _route_post_rotate_secret(request: Request, client_id: str):
    handler = Handler(request)
    if not handler._caller():
        return handler._send(401, {"error": "authentication required"})
    await handler.load_body()
    return await _run(handler, lambda h: h.post_rotate_secret(client_id))

    raise HTTPException(status_code=404, detail={"error": "not found"})


def serve(port):
    """Bind this component for local acceptance. Leave the plumbing alone."""
    import uvicorn
    from fastapi import FastAPI

    app = FastAPI()
    app.include_router(router)
    uvicorn.run(app, host="127.0.0.1", port=port, log_level="error")


if __name__ == "__main__":
    serve(8080)
