"""the system shall Store a bookmark with its url and return it to its owner by id.

Generated by The Factory from its requirement graph.
"""

import json
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

from store import open_store

SERVICE_NAME = 'owners'
SERVICE_VERSION = "1.0.0"
OWNER_HEADER = 'X-Owner'

# Where this component's records live. Provided by the scaffold: put a record
# with store.put(record, owner), read one with store.get(id), list them with
# store.list(owner). Do not hold records in a module-level dict — records must reach the database or they are lost when the process stops, which is the one thing this scaffold exists to prevent.
store = open_store(SERVICE_NAME)


class Handler(BaseHTTPRequestHandler):
    """One method per operation in the contract. The plumbing is done."""

    # -- plumbing: correct, and not yours to change ------------------------

    def log_message(self, *args):
        pass

    def _send(self, status, payload):
        body = json.dumps(payload).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _body(self) -> dict:
        length = int(self.headers.get("Content-Length") or 0)
        if not length:
            return {}
        try:
            return json.loads(self.rfile.read(length) or b"{}")
        except ValueError:
            return {}

    def _caller(self) -> str:
        return self.headers.get('X-Owner', "") if 'X-Owner' else ""

    def _path_id(self) -> str:
        return self.path.rstrip("/").rsplit("/", 1)[-1]

    def do_GET(self):
        self._route("GET")

    def do_POST(self):
        self._route("POST")

    def do_PUT(self):
        self._route("PUT")

    def do_DELETE(self):
        self._route("DELETE")

    def _route(self, method):
        # Any handler that raises would otherwise kill the connection and the
        # component would look unreachable rather than wrong.
        try:
            if method == "GET" and self.path.rstrip("/") == "/health":
                return self.health()
            if method == "POST" and self.path.rstrip("/") == '/owners':
                if not self._caller():
                    return self._send(401, {"error": "an owner is required"})
                return self.create()
            if method == "GET" and self.path.startswith('/owners/'):
                if not self._caller():
                    return self._send(401, {"error": "an owner is required"})
                return self.fetch(self._path_id())
            if method == "GET" and self.path.rstrip("/") == "/no-such-path":
                return self._no_such_path()
            self._send(404, {"error": "not found"})
        except Exception as error:  # noqa: BLE001
            self._send(500, {"error": str(error)})

    # -- the behaviour: this is the part you implement ---------------------

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        self._send(200, {"service": SERVICE_NAME, "version": SERVICE_VERSION})

    def create(self):
        """Store the body as it was sent and answer 201 with the record."""
        body = self._body()
        if not isinstance(body, dict):
            return self._send(400, {"error": "the body must be a JSON object"})
        owner = self._caller()
        stored = store.put(body, owner)
        return self._send(201, stored)

    def fetch(self, record_id):
        """Return the record, 403 when wrong owner, 404 when not found."""
        caller = self._caller()
        if not caller:
            return self._send(401, {"error": "an owner is required"})
        record = store.get(record_id)
        if record is None:
            return self._send(404, {"error": "not found"})
        owner_of_record = store.owner_of(record_id)
        if owner_of_record != caller:
            return self._send(403, {"error": "forbidden"})
        return self._send(200, record)

    def _no_such_path(self):
        """Handle paths the contract does not define."""
        return self._send(404, {"error": "not found"})


import time

RETENTION_DAYS = 30


def _cleanup():
    """Delete records older than RETENTION_DAYS."""
    cutoff = (time.time() - RETENTION_DAYS * 86400).strftime("%Y-%m-%d %H:%M:%S")
    with store._lock, store._connection.cursor() as cursor:
        cursor.execute(
            f'DELETE FROM "{store.schema}".records WHERE created_at < %s',
            (cutoff,),
        )


def serve(port):
    import threading

    server = ThreadingHTTPServer(("127.0.0.1", port), Handler)
    t = threading.Thread(target=_cleanup, daemon=True)
    t.start()
    server.serve_forever()


if __name__ == "__main__":
    serve(8080)
