"""Where this application keeps its records (docs/11 §3).

Generated by The Factory from its scaffold. Not yours to change: the component
modules call `open_store(name)` and use what it returns.

One database schema per service, owned by that service and touched by no other
(D-30). The schema arrives through the numbered `.sql` files in `migrations/`,
applied in order at startup and recorded in the service's own `schema_version`
table, so running against a database that already holds data is the ordinary
case rather than the dangerous one.
"""

import json
import os
import pathlib
import re
import threading

import psycopg

DATABASE_URL = os.environ.get("DATABASE_URL", "")
MIGRATIONS = pathlib.Path(__file__).resolve().parent / "migrations"


class NoDatabase(RuntimeError):
    """DATABASE_URL was not set. Said plainly rather than as a connection error."""


def schema_for(service):
    slug = re.sub(r"[^a-z0-9_]+", "_", (service or "service").lower()).strip("_")
    return "svc_" + (slug or "service")


class Store:
    """Records for one service, in that service's own schema."""

    durable = True

    def __init__(self, service):
        if not DATABASE_URL:
            raise NoDatabase(
                "this component persists to PostgreSQL and DATABASE_URL is not set"
            )
        self.service = service
        self.schema = schema_for(service)
        self._lock = threading.Lock()
        self._connection = psycopg.connect(DATABASE_URL, autocommit=True)
        self.applied = self._migrate()

    # -- schema ------------------------------------------------------------

    def _migrate(self):
        """Apply every migration this schema has not seen, in order."""
        with self._lock, self._connection.cursor() as cursor:
            cursor.execute(f'CREATE SCHEMA IF NOT EXISTS "{self.schema}"')
            cursor.execute(
                f'CREATE TABLE IF NOT EXISTS "{self.schema}".schema_version ('
                "  version text PRIMARY KEY,"
                "  applied_at timestamptz NOT NULL DEFAULT now())"
            )
            cursor.execute(f'SELECT version FROM "{self.schema}".schema_version')
            seen = {row[0] for row in cursor.fetchall()}

            applied = []
            for path in sorted((MIGRATIONS / self.service).glob("*.sql")):
                version = path.name.split("_", 1)[0]
                if version in seen:
                    continue
                cursor.execute(path.read_text())
                cursor.execute(
                    f'INSERT INTO "{self.schema}".schema_version (version) VALUES (%s)'
                    " ON CONFLICT DO NOTHING",
                    (version,),
                )
                applied.append(version)
        return applied

    # -- records -----------------------------------------------------------

    def next_id(self):
        with self._lock, self._connection.cursor() as cursor:
            cursor.execute(f"SELECT nextval('\"{self.schema}\".record_id')")
            return str(cursor.fetchone()[0])

    def put(self, record, owner=""):
        """Store `record` under its "id", and return what was stored.

        The record that comes back carries "id" and "owner", matching the
        contract's 201 response — "the fields that were sent, plus id and
        owner". Keeping the owner only in its column made the response and the
        contract disagree, and two agents following the same contract failed
        each other over it.
        """
        stored = dict(record)
        stored.setdefault("id", self.next_id())
        stored["id"] = str(stored["id"])
        stored["owner"] = str(owner or "")
        with self._lock, self._connection.cursor() as cursor:
            cursor.execute(
                f'INSERT INTO "{self.schema}".records (id, owner, body)'
                " VALUES (%s, %s, %s)"
                " ON CONFLICT (id) DO UPDATE SET owner = EXCLUDED.owner,"
                " body = EXCLUDED.body",
                (stored["id"], stored["owner"], json.dumps(stored)),
            )
        return dict(stored)

    def get(self, record_id):
        with self._lock, self._connection.cursor() as cursor:
            cursor.execute(
                f'SELECT body FROM "{self.schema}".records WHERE id = %s',
                (str(record_id),),
            )
            row = cursor.fetchone()
        return dict(row[0]) if row else None

    def owner_of(self, record_id):
        with self._lock, self._connection.cursor() as cursor:
            cursor.execute(
                f'SELECT owner FROM "{self.schema}".records WHERE id = %s',
                (str(record_id),),
            )
            row = cursor.fetchone()
        return row[0] if row else None

    def list(self, owner=None):
        with self._lock, self._connection.cursor() as cursor:
            if owner is None:
                cursor.execute(
                    f'SELECT body FROM "{self.schema}".records ORDER BY created_at'
                )
            else:
                cursor.execute(
                    f'SELECT body FROM "{self.schema}".records WHERE owner = %s'
                    " ORDER BY created_at",
                    (str(owner),),
                )
            return [dict(row[0]) for row in cursor.fetchall()]

    def delete(self, record_id):
        with self._lock, self._connection.cursor() as cursor:
            cursor.execute(
                f'DELETE FROM "{self.schema}".records WHERE id = %s',
                (str(record_id),),
            )
            return cursor.rowcount > 0


_open = {}


def open_store(service):
    """The store for this service. One per service name, per process."""
    if service not in _open:
        _open[service] = Store(service)
    return _open[service]
