"""Where this application keeps its records (docs/11 §3).

Generated by The Factory from its scaffold. Not yours to change: the component
modules call `open_store(name)` and use what it returns.

One database schema per service, owned by that service and touched by no other
(D-30). The schema arrives through the numbered `.sql` files in `migrations/`,
applied in order at startup and recorded in the service's own `schema_version`
table, so running against a database that already holds data is the ordinary
case rather than the dangerous one.
"""

import json
import os
import pathlib
import re
import threading
import time

import psycopg

# -- the two seams a test needs, and production never touches -----------------
#
# docs/17 W3 asks for fixtures with a pinned clock. Without one, a criterion
# like "a record 31 days old is hard deleted" cannot be exercised at all: the
# test-writer reads the interface, finds no way to make time pass, and answers
# NOT EXECUTABLE — correctly. Measured across one application, that class plus
# "no way to make a dependency unavailable" accounted for every criterion the
# suite could not reach.
#
# Neither seam is reachable over HTTP. A caller cannot move the clock or break
# the storage; only code running inside the process can, which is the acceptance
# environment and nothing else.


class Clock:
    """Where this application gets "now".

    Real time plus an offset. Production never moves the offset and behaves
    exactly as `time.time()`; a test moves it and a record becomes old.
    """

    def __init__(self):
        self._offset = 0.0
        self._lock = threading.Lock()

    def now(self):
        return time.time() + self._offset

    def advance(self, seconds=0, days=0):
        """Move the application's clock forward. For tests."""
        with self._lock:
            self._offset += float(seconds) + float(days) * 86400.0
        return self.now()

    def reset(self):
        with self._lock:
            self._offset = 0.0


clock = Clock()


class StoreUnavailable(RuntimeError):
    """The storage this component depends on is not answering.

    Raised by the seam below rather than by a real outage, so the behaviour a
    requirement asks for when a dependency fails is something a test can
    actually provoke.
    """


_broken = {"storage": False}


def break_storage(broken=True):
    """Make every store operation fail until it is restored. For tests."""
    _broken["storage"] = bool(broken)


def restore_storage():
    break_storage(False)


def _check_available():
    if _broken["storage"]:
        raise StoreUnavailable("the storage this component depends on is unavailable")


DATABASE_URL = os.environ.get("DATABASE_URL", "")
MIGRATIONS = pathlib.Path(__file__).resolve().parent / "migrations"


class NoDatabase(RuntimeError):
    """DATABASE_URL was not set. Said plainly rather than as a connection error."""


def schema_for(service):
    slug = re.sub(r"[^a-z0-9_]+", "_", (service or "service").lower()).strip("_")
    return "svc_" + (slug or "service")


class Store:
    """Records for one service, in that service's own schema."""

    durable = True

    def __init__(self, service, retention_days=None):
        if not DATABASE_URL:
            raise NoDatabase(
                "this component persists to PostgreSQL and DATABASE_URL is not set"
            )
        self.service = service
        self.retention_days = retention_days
        self.schema = schema_for(service)
        self._lock = threading.Lock()
        self._connection = psycopg.connect(DATABASE_URL, autocommit=True)
        self.applied = self._migrate()

    # -- schema ------------------------------------------------------------

    def _migrate(self):
        """Apply every migration this schema has not seen, in order."""
        with self._lock, self._connection.cursor() as cursor:
            cursor.execute(f'CREATE SCHEMA IF NOT EXISTS "{self.schema}"')
            cursor.execute(
                f'CREATE TABLE IF NOT EXISTS "{self.schema}".schema_version ('
                "  version text PRIMARY KEY,"
                "  applied_at timestamptz NOT NULL DEFAULT now())"
            )
            cursor.execute(f'SELECT version FROM "{self.schema}".schema_version')
            seen = {row[0] for row in cursor.fetchall()}

            applied = []
            for path in sorted((MIGRATIONS / self.service).glob("*.sql")):
                version = path.name.split("_", 1)[0]
                if version in seen:
                    continue
                cursor.execute(path.read_text())
                cursor.execute(
                    f'INSERT INTO "{self.schema}".schema_version (version) VALUES (%s)'
                    " ON CONFLICT DO NOTHING",
                    (version,),
                )
                applied.append(version)
        return applied

    # -- records -----------------------------------------------------------

    def next_id(self):
        _check_available()
        with self._lock, self._connection.cursor() as cursor:
            cursor.execute(f"SELECT nextval('\"{self.schema}\".record_id')")
            return str(cursor.fetchone()[0])

    def put(self, record, owner=""):
        """Store `record` under its "id", and return what was stored.

        The record that comes back carries "id" and "owner", matching the
        contract's 201 response — "the fields that were sent, plus id and
        owner". Keeping the owner only in its column made the response and the
        contract disagree, and two agents following the same contract failed
        each other over it.
        """
        stored = dict(record)
        # Not `setdefault`: it evaluates its default eagerly, so a record that
        # already had an id still called next_id() — a wasted `nextval` round
        # trip on every single write, and a sequence full of gaps. Found by
        # watching a running application hand out ids 1 and 3.
        if not stored.get("id"):
            stored["id"] = self.next_id()
        stored["id"] = str(stored["id"])
        stored["owner"] = str(owner or "")
        with self._lock, self._connection.cursor() as cursor:
            # created_at comes from the application's clock, not the database's.
            # A record's age is something a test has to be able to change, and
            # `DEFAULT now()` is the one value in this table nothing can move.
            cursor.execute(
                f'INSERT INTO "{self.schema}".records (id, owner, body, created_at)'
                " VALUES (%s, %s, %s, to_timestamp(%s))"
                " ON CONFLICT (id) DO UPDATE SET owner = EXCLUDED.owner,"
                " body = EXCLUDED.body",
                (stored["id"], stored["owner"], json.dumps(stored), clock.now()),
            )
        return dict(stored)

    def get(self, record_id):
        _check_available()
        self._expire()
        with self._lock, self._connection.cursor() as cursor:
            cursor.execute(
                f'SELECT body FROM "{self.schema}".records WHERE id = %s',
                (str(record_id),),
            )
            row = cursor.fetchone()
        return dict(row[0]) if row else None

    def owner_of(self, record_id):
        _check_available()
        self._expire()
        with self._lock, self._connection.cursor() as cursor:
            cursor.execute(
                f'SELECT owner FROM "{self.schema}".records WHERE id = %s',
                (str(record_id),),
            )
            row = cursor.fetchone()
        return row[0] if row else None

    def list(self, owner=None):
        _check_available()
        self._expire()
        with self._lock, self._connection.cursor() as cursor:
            if owner is None:
                cursor.execute(
                    f'SELECT body FROM "{self.schema}".records ORDER BY created_at'
                )
            else:
                cursor.execute(
                    f'SELECT body FROM "{self.schema}".records WHERE owner = %s'
                    " ORDER BY created_at",
                    (str(owner),),
                )
            return [dict(row[0]) for row in cursor.fetchall()]

    def delete(self, record_id):
        _check_available()
        with self._lock, self._connection.cursor() as cursor:
            cursor.execute(
                f'DELETE FROM "{self.schema}".records WHERE id = %s',
                (str(record_id),),
            )
            return cursor.rowcount > 0

    def _expire(self):
        """Drop records older than the retention the requirement asked for.

        Swept on read rather than by a background job: a component this size has
        no scheduler, and a record that is gone the moment anybody looks is
        indistinguishable from one a job removed — which is what the criterion
        actually asserts.
        """
        if not self.retention_days:
            return
        cutoff = clock.now() - self.retention_days * 86400.0
        with self._lock, self._connection.cursor() as cursor:
            cursor.execute(
                f'DELETE FROM "{self.schema}".records WHERE created_at < to_timestamp(%s)',
                (cutoff,),
            )


_open = {}


def open_store(service, retention_days=None):
    """The store for this service. One per service name, per process."""
    if service not in _open:
        _open[service] = Store(service, retention_days)
    return _open[service]
