"""the system shall store a subscription with its plan name and started date and return it by id.

Generated by The Factory from its requirement graph.
"""

import json
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

import telemetry
from store import StoreUnavailable, open_store
from store import counters as store_counters

SERVICE_NAME = 'subscriptions'
SERVICE_VERSION = "1.0.0"
# What the graph calls the thing this component is about, and where it lives.
# Telemetry is labelled with them so a metric joins back to the requirements it
# serves (docs/15 §1) — the same names `graph.subjects` indexes, because two
# derivations of one name is how a join quietly stops finding anything.
ENTITY = 'subscription'
BASE_PATH = '/subscriptions'
# How long a record is kept, from the requirement's retention answer. None means
# forever. The store sweeps on read; no handler has to remember.
RETENTION_DAYS = 30
# Columns derived from what the requirements named (docs/11 §4). The record is
# stored whole either way; these let the database be queried through them.
RECORD_FIELDS = ['plan_name', 'started_date']
# How many times the store tries before giving up. More than one only when a
# requirement answered "retry, then reject" — the retry-with-backoff Pattern.
STORE_ATTEMPTS = 3
# The fields the requirement named, and what each must hold. Enforced in the
# plumbing rather than asked of the handler: validation is derivable from the
# contract, and a check that is derivable is the factory's to make. "Any JSON
# object" was honest for a factory that could not type anything — and it is
# why nothing could ever verify that an amount was an amount.
REQUIRED_FIELDS = ['plan_name', 'started_date']
FIELD_TYPES = {'started_date': 'date-time'}
OWNER_HEADER = 'X-Owner'

# Where this component's records live. Provided by the scaffold: put a record
# with store.put(record, owner), read one with store.get(id), list them with
# store.list(owner). Do not hold records in a module-level dict — records must reach the database or they are lost when the process stops, which is the one thing this scaffold exists to prevent.
store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS)


class Handler(BaseHTTPRequestHandler):
    """One method per operation in the contract. The plumbing is done."""

    # -- plumbing: correct, and not yours to change ------------------------

    def log_message(self, *args):
        pass

    def _send(self, status, payload=None):
        # 204 means "no content", and a 204 carrying a JSON body is a malformed
        # response that some clients accept and some hang on. The plumbing
        # handles it so no handler has to remember.
        body = b"" if status == 204 else json.dumps(payload).encode()
        self.send_response(status)
        if body:
            self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if body:
            self.wfile.write(body)
        # One counter per outcome, named the same way in every component
        # (docs/15 §2). In the plumbing rather than in a handler, so it counts
        # whatever the component answers including the answers it did not mean.
        telemetry.count(f"http_{status}")
        # And per contract operation, which is the anchor of the requirement
        # join (docs/15 §1, §2): operations are named by contracts, contracts
        # are edges in the graph, so a burn traces back to the requirements it
        # serves without anybody maintaining a naming convention. The label set
        # is a literal, so cardinality is bounded by the Pattern rather than by
        # whatever a handler decides to pass.
        operation = self._operation()
        if operation:
            telemetry.count(f"{operation}.{'error' if status >= 400 else 'ok'}")

    def _operation(self):
        """Which contract operation this request is, as the graph names it."""
        tail = self.path.rstrip("/").rsplit("/", 1)[-1]
        collection = ("/" + tail) == BASE_PATH or not tail
        verb = {"POST": "store", "PUT": "store", "DELETE": "delete"}.get(
            self.command, "list" if collection else "read"
        )
        return f"{ENTITY}.{verb}" if ENTITY else ""

    def _body(self) -> dict:
        # Parsed once and remembered: the stream can only be read once, and
        # the plumbing validates the same bytes the handler then stores.
        if not hasattr(self, "_parsed_body"):
            length = int(self.headers.get("Content-Length") or 0)
            if not length:
                self._parsed_body = {}
            else:
                try:
                    self._parsed_body = json.loads(self.rfile.read(length) or b"{}")
                except ValueError:
                    self._parsed_body = {}
        return self._parsed_body

    def _malformed(self):
        """What is wrong with this body, or None. The error names the field.

        In the plumbing because it is derived from the contract: the required
        fields are the requirement's own "with its …" clause, and the types
        come from what the names declare. A handler never sees a body that
        fails its contract.
        """
        body = self._body()
        if not isinstance(body, dict):
            return {"error": "the body must be a JSON object"}
        missing = [name for name in REQUIRED_FIELDS if name not in body]
        if missing:
            return {"error": "missing required field(s): " + ", ".join(missing),
                    "fields": missing}
        for name, kind in FIELD_TYPES.items():
            if name not in body:
                continue
            value = body[name]
            if kind == "integer" and (isinstance(value, bool)
                                      or not isinstance(value, int)):
                return {"error": f"{name} must be a whole number"}
            if kind == "date-time":
                from datetime import datetime

                try:
                    datetime.fromisoformat(str(value))
                except ValueError:
                    return {"error": f"{name} must be an ISO 8601 date-time"}
        return None

    def _caller(self) -> str:
        return self.headers.get('X-Owner', "") if 'X-Owner' else ""

    def _path_id(self) -> str:
        return self.path.rstrip("/").rsplit("/", 1)[-1]

    def do_GET(self):
        self._route("GET")

    def do_POST(self):
        self._route("POST")

    def do_PUT(self):
        self._route("PUT")

    def do_DELETE(self):
        self._route("DELETE")

    def _route(self, method):
        # Any handler that raises would otherwise kill the connection and the
        # component would look unreachable rather than wrong.
        try:
            if method == "GET" and self.path.rstrip("/") == "/health":
                return self.health()
            if method == "POST" and self.path.rstrip("/") == '/subscriptions':
                if not self._caller():
                    return self._send(401, {"error": "an owner is required"})
                problem = self._malformed()
                if problem is not None:
                    return self._send(400, problem)
                return self.create()
            if method == "GET" and self.path.startswith('/subscriptions/'):
                if not self._caller():
                    return self._send(401, {"error": "an owner is required"})
                return self.fetch(self._path_id())
            self._send(404, {"error": "not found"})
        except StoreUnavailable as error:
            # The dependency is down, which is not this component being wrong.
            # 503 rather than 500 so a caller can tell "try again" from "this
            # request will never work" — and so the criterion a requirement
            # derives about a failed dependency has something to assert.
            self._send(503, {"error": str(error)})
        except Exception as error:  # noqa: BLE001
            self._send(500, {"error": str(error)})

    # -- the behaviour: this is the part you implement ---------------------

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        self._send(200, {"service": SERVICE_NAME, "version": SERVICE_VERSION,
                         # What this component has done, so behaviour invisible
                         # from a single response — a retry, a refusal — can
                         # still be seen.
                         "counters": dict(telemetry.snapshot(), **store_counters)})

    def create(self):
        """Store the body as it was sent and answer 201 with the record.

        Store every field the caller sent, unchanged, with
        `store.put(record, owner)` — which fills in "id" and "owner" and
        returns what was stored, which is exactly what the contract's 201
        response describes ("the fields that were sent, plus id and owner").

        The body has already been validated by `_malformed()` before we get
        here: it is a JSON object carrying every required field of the right
        type. Nothing to require ourselves — the contract names no particular
        field, so insisting on one would refuse requests the criteria expect us
        to accept (extra fields are stored and returned as sent).

        The owner comes from the X-Owner header; an absent owner was already
        refused with 401 by `_route`, so here it is present.
        """
        record = self._body()
        if not isinstance(record, dict):
            # Defensive: _malformed() above should have returned 400 first.
            return self._send(400, {"error": "the body must be a JSON object"})
        stored = store.put(record, owner=self._caller())
        return self._send(201, stored)

    def fetch(self, record_id):
        """Answer 200 with the record, 404 when there is none, and 403 when the caller is not the record's owner.

        `store.get(record_id)` returns the record or None;
        `store.owner_of(record_id)` returns who stored it.
        """
        # A record that was never created is nobody's — the criterion names it
        # 404, so check existence first and let a missing record answer on its
        # own before we ask "is this yours?".
        record = store.get(record_id)
        if record is None:
            return self._send(404, {"error": "no such record"})
        owner = self._caller()
        if store.owner_of(record_id) != owner:
            # The record exists but belongs to somebody else. This identified
            # caller may not reach it — 403.
            return self._send(403, {"error": "not your record"})
        return self._send(200, record)


def serve(port):
    ThreadingHTTPServer(("127.0.0.1", port), Handler).serve_forever()


if __name__ == "__main__":
    serve(8080)
