"""The system shall store a thread in a forum and return the thread by id, detecting retries idempotently..

Generated by The Factory from its requirement graph.
"""

import hashlib
from threading import Lock

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse, Response

import telemetry
from store import StoreUnavailable, open_store
from store import counters as store_counters


# Idempotency-Key tracking for POST /threads. The contract leaves the storage
# format to us and no idempotency table exists in this schema, so we keep a
# process-lifetime map from key -> replayed response. A retry with the same
# key returns exactly what was first returned (idempotency-key@1).
_idempotent_lock = Lock()
_idempotent: dict[str, dict] = {}


def _content_hash(record: dict) -> str:
    """Stable fingerprint of a thread's meaningful fields for duplicate detection."""
    payload = record.get("title") + "\x00" + record.get("content")
    return hashlib.sha256(payload.encode()).hexdigest()

SERVICE_NAME = 'threads'
SERVICE_VERSION = "1.0.0"
ENTITY = 'thread'
BASE_PATH = '/threads'
RETENTION_DAYS = None
RECORD_FIELDS = ['title', 'content']
STORE_ATTEMPTS = 1
REQUIRED_FIELDS = []
FIELD_TYPES = {}
AMOUNT_ROUNDING = None
REFERENCES = []
AUTH_SCHEME = 'bearer'
OWNER_HEADER = 'Authorization'

store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS)


class Handler:
    """Contract plumbing and behaviour handlers. Complete the TODO methods only."""

    def __init__(self, request: Request):
        self.request = request
        self._parsed_body = None

    async def load_body(self):
        if self._parsed_body is None:
            try:
                self._parsed_body = await self.request.json()
            except Exception:
                self._parsed_body = {}
        return self._parsed_body

    def _send(self, status, payload=None):
        if status == 204:
            response = Response(status_code=204)
        else:
            response = JSONResponse(status_code=status, content=payload)
        telemetry.count(f"http_{status}")
        operation = self._operation()
        if operation:
            telemetry.count(
                f"{operation}.{'error' if status >= 400 else 'ok'}"
            )
        return response

    def _operation(self):
        path = self.request.url.path.rstrip("/")
        collection = path == BASE_PATH.rstrip("/")
        verb = {"POST": "store", "PUT": "store", "PATCH": "update", "DELETE": "delete"}.get(
            self.request.method, "list" if collection else "read"
        )
        return f"{ENTITY}.{verb}" if ENTITY else ""

    def _body(self) -> dict:
        return self._parsed_body if self._parsed_body is not None else {}

    def _query(self) -> dict:
        """Query-string fields for GET/HEAD — not a JSON body."""
        return {key: value for key, value in self.request.query_params.multi_items()}

    def _malformed(self):
        body = self._body()
        if not isinstance(body, dict):
            return {"error": "the body must be a JSON object"}
        missing = [name for name in REQUIRED_FIELDS if name not in body]
        if missing:
            return {
                "error": "missing required field(s): " + ", ".join(missing),
                "fields": missing,
            }
        for name, kind in FIELD_TYPES.items():
            if name not in body:
                continue
            value = body[name]
            if kind == "integer":
                if isinstance(value, bool):
                    return {"error": f"{name} must be a whole number"}
                if AMOUNT_ROUNDING:
                    if not isinstance(value, (int, float)):
                        return {"error": f"{name} must be a whole number"}
                elif not isinstance(value, int):
                    return {"error": f"{name} must be a whole number"}
            if kind == "date-time":
                from datetime import datetime
                try:
                    datetime.fromisoformat(str(value))
                except ValueError:
                    return {"error": f"{name} must be an ISO 8601 date-time"}
        if AMOUNT_ROUNDING:
            from decimal import ROUND_HALF_EVEN, ROUND_HALF_UP, Decimal
            mode = ROUND_HALF_UP if AMOUNT_ROUNDING == "half_up" else ROUND_HALF_EVEN
            for name, kind in FIELD_TYPES.items():
                if kind != "integer" or name not in body:
                    continue
                value = body[name]
                if isinstance(value, float):
                    body[name] = int(
                        (Decimal(str(value)) * 100).to_integral_value(rounding=mode)
                    )
        for ref in REFERENCES:
            field = ref.get("field")
            service = ref.get("service")
            if not field or not service or field not in body:
                continue
            if open_store(service).get(str(body[field])) is None:
                return {
                    "error": (
                        f"{field} names a {ref.get('resource', 'record')} "
                        f"that was never stored"
                    ),
                    "fields": [field],
                }
        return None

    def _caller(self) -> str:
        if not 'Authorization':
            return ""
        raw = self.request.headers.get('Authorization', "")
        if AUTH_SCHEME == "bearer":
            if not raw.lower().startswith("bearer "):
                return ""
            token = raw[7:].strip()
            return token if token else ""
        return raw

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        return self._send(
            200,
            {
                "service": SERVICE_NAME,
                "version": SERVICE_VERSION,
                "counters": dict(telemetry.snapshot(), **store_counters),
            },
        )

    def create(self):
        """Store the thread and answer 201 with it, detecting retries idempotently.

        The contract's POST /threads takes no required field, so we store every
        field the caller sent unchanged through `store.put(record, owner)`, which
        fills in "id" and "owner" and returns exactly what the 201 response
        describes. A body that is not an object was already refused by
        `_malformed()` before this runs; we refuse only a null/empty body here so
        there is nothing to store.

        Duplicate handling, per build_guidance:
          * Idempotency-Key — if the caller sends one and we have stored a reply
            for it, replay that exact response (idempotency-key@1) instead of
            creating a duplicate.
          * Concurrent duplicates — if identical content is already stored, reject
            with 409 Conflict rather than overwriting it.

        The caller's id is used as the owner so ownership follows whoever created
        the thread; GET /threads/{id} is public per the sealed contract and does
        not check ownership.
        """
        body = self._body()
        if not isinstance(body, dict) or not body:
            return self._send(400, {"error": "the body must be a non-empty JSON object"})

        idempotency_key = body.get("idempotency_key")
        thread = {name: value for name, value in body.items() if name != "idempotency_key"}

        # 1. Idempotent replay of a prior response to the same key.
        if idempotency_key is not None and str(idempotency_key):
            with _idempotent_lock:
                stored = _idempotent.get(str(idempotency_key))
            if stored is not None:
                return self._send(200, stored)

        # 2. Reject concurrent duplicates of identical content (409 Conflict).
        existing_id = self._existing_by_content(thread)
        if existing_id is not None:
            return self._send(
                409,
                {"error": "a thread with identical content already exists", "id": existing_id},
            )

        owner = str(self._caller()) or ""
        stored = store.put(thread, owner)

        # Record the reply so a retry with the same Idempotency-Key replays it.
        if idempotency_key is not None and str(idempotency_key):
            key = str(idempotency_key)
            with _idempotent_lock:
                _idempotent[key] = stored

        return self._send(201, stored)

    def _existing_by_content(self, thread: dict):
        """Return the id of a stored thread with identical title+content, else None."""
        try:
            digest = _content_hash(thread)
        except (TypeError, ValueError):
            return None
        for record in store.list():
            if str(record.get("id")) == "null":
                continue
            if _content_hash(record) == digest:
                return str(record.get("id"))
        return None

    def fetch(self, record_id):
        """Answer 200 with the thread, 404 when there is none.

        `store.get` returns the record or None; we mask "not found" as 404 so a
        missing id leaks nothing about what exists (build_guidance). The contract's
        GET /threads/{id} is public and does not check ownership, so any stored
        thread with that id is returned.
        """
        record = store.get(record_id)
        if record is None:
            return self._send(404, {"error": "not found"})
        return self._send(200, record)



router = APIRouter()


async def _run(handler, call):
    try:
        return call(handler)
    except StoreUnavailable as error:
        return handler._send(503, {"error": str(error)})
    except Exception as error:  # noqa: BLE001
        return handler._send(500, {"error": str(error)})


@router.get("/health")
async def _route_health(request: Request):
    handler = Handler(request)
    return await _run(handler, lambda h: h.health())

@router.post(BASE_PATH)
async def _route_create(request: Request):
    handler = Handler(request)
    await handler.load_body()
    problem = handler._malformed()
    if problem is not None:
        return handler._send(400, problem)
    return await _run(handler, lambda h: h.create())

@router.get(BASE_PATH + "/{record_id}")
async def _route_fetch(request: Request, record_id: str):
    handler = Handler(request)
    handler._parsed_body = {'id': record_id}
    return await _run(handler, lambda h: h.fetch(record_id))

    raise HTTPException(status_code=404, detail={"error": "not found"})


def serve(port):
    """Bind this component for local acceptance. Leave the plumbing alone."""
    import uvicorn
    from fastapi import FastAPI

    app = FastAPI()
    app.include_router(router)
    uvicorn.run(app, host="127.0.0.1", port=port, log_level="error")


if __name__ == "__main__":
    serve(8080)
