-- reminders: initial schema, generated by The Factory (docs/11 §5).
--
-- Expand-phase and additive: every statement is IF NOT EXISTS, so re-applying
-- this file to a database already at this version changes nothing. That is not
-- politeness — it is the property the migration check measures.

CREATE SCHEMA IF NOT EXISTS "svc_reminders";

CREATE SEQUENCE IF NOT EXISTS "svc_reminders".record_id AS bigint START 1;

CREATE TABLE IF NOT EXISTS "svc_reminders".records (
    id         text PRIMARY KEY,
    -- Who stored it. Empty where the contract declares no auth_header.
    owner      text NOT NULL DEFAULT '',
    -- The record as the caller sent it, plus its id. Held whole because the
    -- contract names no required fields: a column per field would refuse
    -- requests the criteria expect the component to accept.
    body       jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS records_owner_idx ON "svc_reminders".records (owner);
