"""the system shall Drop current-state narration that is not required behaviour; operator drive: proceed with greenfield defaults Currently: Behaviours that did not hold: Scenario: Domain Event Recording on Write Success; Scenario: Successful domain write triggers event recording — repair stalled after 5 cycle(s): the same checks failed identically.

Generated by The Factory from its requirement graph.
"""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse, Response

import telemetry
from store import StoreUnavailable, open_store
from store import counters as store_counters

SERVICE_NAME = 'domains'
SERVICE_VERSION = "1.0.0"
ENTITY = 'domain'
BASE_PATH = '/domains'
RETENTION_DAYS = None
RECORD_FIELDS = ['event_type', 'payload', 'timestamp']
STORE_ATTEMPTS = 1
IDENTITY_FIELD = None
UNIQUE_FIELDS = []
REQUIRED_FIELDS = []
FIELD_TYPES = {}
AMOUNT_ROUNDING = None
REFERENCES = []
AUTH_SCHEME = 'plain'
IDEMPOTENCY_HEADER = ''
OWNER_HEADER = 'X-Owner-Id'

store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS)
_IDEMPOTENCY_KEYS = {}


class Handler:
    """Contract plumbing and behaviour handlers. Complete the TODO methods only."""

    def __init__(self, request: Request):
        self.request = request
        self._parsed_body = None

    async def load_body(self):
        if self._parsed_body is None:
            try:
                raw = await self.request.body()
            except Exception:
                raw = b""
            self._raw_body = raw or b""
            try:
                import json as _json
                self._parsed_body = _json.loads(self._raw_body) if self._raw_body else {}
            except Exception:
                self._parsed_body = {}
        return self._parsed_body

    def _send(self, status, payload=None):
        if status == 204:
            response = Response(status_code=204)
        else:
            response = JSONResponse(status_code=status, content=payload)
        telemetry.count(f"http_{status}")
        operation = self._operation()
        if operation:
            telemetry.count(
                f"{operation}.{'error' if status >= 400 else 'ok'}"
            )
        return response

    def _operation(self):
        path = self.request.url.path.rstrip("/")
        collection = path == BASE_PATH.rstrip("/")
        verb = {"POST": "store", "PUT": "store", "PATCH": "update", "DELETE": "delete"}.get(
            self.request.method, "list" if collection else "read"
        )
        return f"{ENTITY}.{verb}" if ENTITY else ""

    def _body(self) -> dict:
        return self._parsed_body if self._parsed_body is not None else {}

    def _query(self) -> dict:
        """Query-string fields for GET/HEAD — not a JSON body."""
        return {key: value for key, value in self.request.query_params.multi_items()}

    def _malformed(self):
        body = self._body()
        if not isinstance(body, dict):
            return {"error": "the body must be a JSON object"}
        missing = [name for name in REQUIRED_FIELDS if name not in body]
        if missing:
            return {
                "error": "missing required field(s): " + ", ".join(missing),
                "fields": missing,
            }
        for name, kind in FIELD_TYPES.items():
            if name not in body:
                continue
            value = body[name]
            if kind == "integer":
                if isinstance(value, bool):
                    return {"error": f"{name} must be a whole number"}
                if AMOUNT_ROUNDING:
                    if not isinstance(value, (int, float)):
                        return {"error": f"{name} must be a whole number"}
                elif not isinstance(value, int):
                    return {"error": f"{name} must be a whole number"}
            if kind == "date-time":
                from datetime import datetime
                try:
                    datetime.fromisoformat(str(value))
                except ValueError:
                    return {"error": f"{name} must be an ISO 8601 date-time"}
        if AMOUNT_ROUNDING:
            from decimal import ROUND_HALF_EVEN, ROUND_HALF_UP, Decimal
            mode = ROUND_HALF_UP if AMOUNT_ROUNDING == "half_up" else ROUND_HALF_EVEN
            for name, kind in FIELD_TYPES.items():
                if kind != "integer" or name not in body:
                    continue
                value = body[name]
                if isinstance(value, float):
                    body[name] = int(
                        (Decimal(str(value)) * 100).to_integral_value(rounding=mode)
                    )
        for ref in REFERENCES:
            field = ref.get("field")
            service = ref.get("service")
            if not field or not service or field not in body:
                continue
            if open_store(service).get(str(body[field])) is None:
                return {
                    "error": (
                        f"{field} names a {ref.get('resource', 'record')} "
                        f"that was never stored"
                    ),
                    "fields": [field],
                }
        return None

    def _caller(self) -> str:
        if not 'X-Owner-Id':
            return ""
        raw = self.request.headers.get('X-Owner-Id', "")
        if AUTH_SCHEME == "bearer":
            if not raw.lower().startswith("bearer "):
                return ""
            token = raw[7:].strip()
            return token if token else ""
        return raw

    def _signature_ok(self) -> bool:
        header_name = 'X-Owner-Id'
        if not header_name or "signature" not in header_name.lower():
            return True
        import hashlib
        import hmac
        import os
        presented = (self.request.headers.get(header_name) or "").strip()
        if not presented:
            return False
        secret = os.environ.get("WEBHOOK_SECRET", "factory-webhook-secret")
        raw = getattr(self, "_raw_body", b"") or b""
        digest = hmac.new(secret.encode("utf-8"), raw, hashlib.sha256).hexdigest()
        return hmac.compare_digest("sha256=" + digest, presented)

    def _idempotency_key(self) -> str:
        """Idempotency-Key from the request header when the contract requires it.

        Criteria and the Try-it pack send the header. Do not read a body field
        named ``idempotency_key`` — that is not the contract surface.
        """
        if not IDEMPOTENCY_HEADER:
            return ""
        return (self.request.headers.get(IDEMPOTENCY_HEADER) or "").strip()

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        return self._send(
            200,
            {
                "service": SERVICE_NAME,
                "version": SERVICE_VERSION,
                "counters": dict(telemetry.snapshot(), **store_counters),
            },
        )

    def post_events(self):
        """POST /domains/events, as the contract describes it.

        The route, the auth guard and the path parameters are already
        derived; what belongs here is the behaviour and the response.

        Read a JSON body with self._body() when the contract sends one.

        Responses the contract names:
          201: Domain event successfully recorded.
          400: Invalid event payload or missing required fields.
        """
        body = self._body()
        if not isinstance(body, dict):
            return self._send(400, {"error": "the body must be a JSON object"})
        missing = [name for name in ("event_type", "payload") if name not in body]
        if missing:
            return self._send(
                400,
                {
                    "error": "missing required field(s): " + ", ".join(missing),
                    "fields": missing,
                },
            )
        record = {
            "event_type": body["event_type"],
            "payload": body["payload"],
            "timestamp": body.get("timestamp"),
        }
        stored = store.put(record, self._caller())
        return self._send(201, dict(stored))

    def get_events_by_id(self, id):
        """GET /domains/events/{id}, as the contract describes it.

        The route, the auth guard and the path parameters are already
        derived; what belongs here is the behaviour and the response.

        `id` is supplied by the route from the URL path segment.

        Responses the contract names:
          200: Successfully retrieved domain event details.
          404: Domain event not found.
        """
        stored = store.get(id)
        if stored is None:
            return self._send(404, {"error": "not found"})
        return self._send(200, dict(stored))



router = APIRouter()


async def _run(handler, call):
    try:
        return call(handler)
    except StoreUnavailable as error:
        return handler._send(503, {"error": str(error)})
    except Exception as error:  # noqa: BLE001
        return handler._send(500, {"error": str(error)})


@router.get("/health")
async def _route_health(request: Request):
    handler = Handler(request)
    return await _run(handler, lambda h: h.health())

@router.post('/domains/events')
async def _route_post_events(request: Request):
    handler = Handler(request)
    if not handler._caller():
        return handler._send(401, {"error": "an owner is required"})
    await handler.load_body()
    return await _run(handler, lambda h: h.post_events())

@router.get('/domains/events/{id}')
async def _route_get_events_by_id(request: Request, id: str):
    handler = Handler(request)
    if not handler._caller():
        return handler._send(401, {"error": "an owner is required"})
    return await _run(handler, lambda h: h.get_events_by_id(id))

    raise HTTPException(status_code=404, detail={"error": "not found"})


def serve(port):
    """Bind this component for local acceptance. Leave the plumbing alone."""
    import uvicorn
    from fastapi import FastAPI

    app = FastAPI()
    app.include_router(router)
    uvicorn.run(app, host="127.0.0.1", port=port, log_level="error")


if __name__ == "__main__":
    serve(8080)
