"""the system shall record a domain event when a write succeeds and make that event available to subscribers.

Generated by The Factory from its requirement graph.
"""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse, Response

import telemetry
from store import StoreUnavailable, open_store
from store import counters as store_counters
import logging
import os
import time
import hashlib

SERVICE_NAME = 'domains'
SERVICE_VERSION = "1.0.0"
ENTITY = 'domain'
BASE_PATH = '/domains'
RETENTION_DAYS = None
RECORD_FIELDS = ['name', 'occurred_at']
STORE_ATTEMPTS = 1
IDENTITY_FIELD = None
UNIQUE_FIELDS = []
REQUIRED_FIELDS = []
FIELD_TYPES = {}
AMOUNT_ROUNDING = None
REFERENCES = []
AUTH_SCHEME = 'bearer'
IDEMPOTENCY_HEADER = 'Idempotency-Key'
OWNER_HEADER = 'Authorization'

store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS)
_IDEMPOTENCY_KEYS = {}


class Handler:
    """Contract plumbing and behaviour handlers. Complete the TODO methods only."""

    def __init__(self, request: Request):
        self.request = request
        self._parsed_body = None

    async def load_body(self):
        if self._parsed_body is None:
            try:
                self._parsed_body = await self.request.json()
            except Exception:
                self._parsed_body = {}
        return self._parsed_body

    def _send(self, status, payload=None):
        if status == 204:
            response = Response(status_code=204)
        else:
            response = JSONResponse(status_code=status, content=payload)
        telemetry.count(f"http_{status}")
        operation = self._operation()
        if operation:
            telemetry.count(
                f"{operation}.{'error' if status >= 400 else 'ok'}"
            )
        return response

    def _operation(self):
        path = self.request.url.path.rstrip("/")
        collection = path == BASE_PATH.rstrip("/")
        verb = {"POST": "store", "PUT": "store", "PATCH": "update", "DELETE": "delete"}.get(
            self.request.method, "list" if collection else "read"
        )
        return f"{ENTITY}.{verb}" if ENTITY else ""

    def _body(self) -> dict:
        return self._parsed_body if self._parsed_body is not None else {}

    def _query(self) -> dict:
        """Query-string fields for GET/HEAD — not a JSON body."""
        return {key: value for key, value in self.request.query_params.multi_items()}

    def _malformed(self):
        body = self._body()
        if not isinstance(body, dict):
            return {"error": "the body must be a JSON object"}
        missing = [name for name in REQUIRED_FIELDS if name not in body]
        if missing:
            return {
                "error": "missing required field(s): " + ", ".join(missing),
                "fields": missing,
            }
        for name, kind in FIELD_TYPES.items():
            if name not in body:
                continue
            value = body[name]
            if kind == "integer":
                if isinstance(value, bool):
                    return {"error": f"{name} must be a whole number"}
                if AMOUNT_ROUNDING:
                    if not isinstance(value, (int, float)):
                        return {"error": f"{name} must be a whole number"}
                elif not isinstance(value, int):
                    return {"error": f"{name} must be a whole number"}
            if kind == "date-time":
                from datetime import datetime
                try:
                    datetime.fromisoformat(str(value))
                except ValueError:
                    return {"error": f"{name} must be an ISO 8601 date-time"}
        if AMOUNT_ROUNDING:
            from decimal import ROUND_HALF_EVEN, ROUND_HALF_UP, Decimal
            mode = ROUND_HALF_UP if AMOUNT_ROUNDING == "half_up" else ROUND_HALF_EVEN
            for name, kind in FIELD_TYPES.items():
                if kind != "integer" or name not in body:
                    continue
                value = body[name]
                if isinstance(value, float):
                    body[name] = int(
                        (Decimal(str(value)) * 100).to_integral_value(rounding=mode)
                    )
        for ref in REFERENCES:
            field = ref.get("field")
            service = ref.get("service")
            if not field or not service or field not in body:
                continue
            if open_store(service).get(str(body[field])) is None:
                return {
                    "error": (
                        f"{field} names a {ref.get('resource', 'record')} "
                        f"that was never stored"
                    ),
                    "fields": [field],
                }
        return None

    def _caller(self) -> str:
        if not 'Authorization':
            return ""
        raw = self.request.headers.get('Authorization', "")
        if AUTH_SCHEME == "bearer":
            if not raw.lower().startswith("bearer "):
                return ""
            token = raw[7:].strip()
            return token if token else ""
        return raw

    def _idempotency_key(self) -> str:
        """Idempotency-Key from the request header when the contract requires it.

        Criteria and the Try-it pack send the header. Do not read a body field
        named ``idempotency_key`` — that is not the contract surface.
        """
        if not IDEMPOTENCY_HEADER:
            return ""
        return (self.request.headers.get(IDEMPOTENCY_HEADER) or "").strip()

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        return self._send(
            200,
            {
                "service": SERVICE_NAME,
                "version": SERVICE_VERSION,
                "counters": dict(telemetry.snapshot(), **store_counters),
            },
        )

    def post_events(self):
        """TODO: POST /domains/events, as the contract describes it.

        The route, the auth guard and the path parameters are already
        derived; what belongs here is the behaviour and the response.

        Read a JSON body with self._body() when the contract sends one.

        Responses the contract names:
          201: event recorded on a successful write
          401: no caller was identified
        """
        body = self._body()

        name = body.get("name")
        if not isinstance(name, str) or not name:
            return self._send(400, {"error": 'missing required field "name"'})

        occurred_at = iso_now(body.get("occurred_at"))

        record = {
            "event_type": body.get("event_type", ""),
            "aggregate_id": "" if not isinstance(body.get("source_id"), str) else body["source_id"],
            "payload": body.get("payload") or {},
            "name": name,
            "occurred_at": occurred_at,
        }
        stored = store.put(record, self._caller())

        key = self._idempotency_key()
        if key:
            digest = hashlib.sha256((self._caller() + "|" + key).encode()).hexdigest()
            _IDEMPOTENCY_CACHE["idem-" + digest] = {
                "event_id": stored["id"],
                "occurred_at": occurred_at,
                "name": name,
            }

        return self._send(
            201,
            {
                "id": stored["id"],
                "name": name,
                "occurred_at": occurred_at,
            },
        )

    def get_events_by_id(self, id):
        """TODO: GET /domains/events/{id}, as the contract describes it.

        The route, the auth guard and the path parameters are already
        derived; what belongs here is the behaviour and the response.

        Read inputs with self._query() — this is a GET/HEAD and the
        contract's parameters are query string fields, not a JSON body.

        Responses the contract names:
          200: the recorded event available to a subscriber
          401: no caller was identified
          404: no such record
        """
        row = store.get(id) if store.applied else None
        record = dict(row) if isinstance(row, dict) else {}

        name = record.get("name")
        if not isinstance(name, str) or not name:
            return self._send(404, {"error": "no such record"})

        return self._send(200, {
            "id": row["id"],
            "name": name,
            "occurred_at": record.get("occurred_at"),
        })

    def get_events(self):
        """TODO: GET /domains/events, as the contract describes it.

        The route, the auth guard and the path parameters are already
        derived; what belongs here is the behaviour and the response.

        Read inputs with self._query() — this is a GET/HEAD and the
        contract's parameters are query string fields, not a JSON body.

        Responses the contract names:
          200: each recorded domain event available to subscribers
          401: no caller was identified
        """
        since_raw = self._query().get("since")
        limit_raw = self._query().get("limit")

        try:
            since_id = int(since_raw) if since_raw else None
        except (TypeError, ValueError):
            since_id = None
        try:
            raw_limit = int(limit_raw) if limit_raw else _EVENT_PAGE_SIZE
        except (TypeError, ValueError):
            raw_limit = _EVENT_PAGE_SIZE

        limit = max(1, min(raw_limit, _EVENT_MAX_PAGE))

        rows = store.list() if store.applied else []
        # `rows` (the full list, ordered by created_at) feeds the comprehension;
        # `row` names each stored record so idempotency-cache stubs — which carry
        # no `name` field and are not domain events — never reach subscribers.
        events = [
            {
                "id": row.get("id"),
                "name": row.get("name"),
                "occurred_at": row.get("occurred_at"),
            }
            for row in rows
            if isinstance(row, dict) and bool(row.get("name"))
        ]

        # `since` is an exclusive lower bound on the numeric id; ids are already
        # ordered by created_at at store time.
        events = [e for e in events if since_id is None or float(e["id"]) > since_id]
        events = sorted(events, key=lambda e: float(e["id"]))
        page = events[since_id:] if since_id is not None else events
        page = page[:limit]

        last = next((e for e in reversed(page) if "id" in e), ({"id": None} if since_id is None else {"id": since_id}))
        body = {
            "events": [
                {"id": e["id"], "name": e["name"], "occurred_at": e["occurred_at"]}
                for e in page
            ],
            "cursor": last["id"],
            "count": len(page),
            "next_cursor": encode_cursor(last["id"]),
        }
        return self._send(200, body)



router = APIRouter()


async def _run(handler, call):
    try:
        return call(handler)
    except StoreUnavailable as error:
        return handler._send(503, {"error": str(error)})
    except Exception as error:  # noqa: BLE001
        return handler._send(500, {"error": str(error)})


@router.get("/health")
async def _route_health(request: Request):
    handler = Handler(request)
    return await _run(handler, lambda h: h.health())

@router.post('/domains/events')
async def _route_post_events(request: Request):
    handler = Handler(request)
    if not handler._caller():
        return handler._send(401, {"error": "authentication required"})
    await handler.load_body()
    return await _run(handler, lambda h: h.post_events())

@router.get('/domains/events/{id}')
async def _route_get_events_by_id(request: Request, id: str):
    handler = Handler(request)
    if not handler._caller():
        return handler._send(401, {"error": "authentication required"})
    return await _run(handler, lambda h: h.get_events_by_id(id))

@router.get('/domains/events')
async def _route_get_events(request: Request):
    handler = Handler(request)
    if not handler._caller():
        return handler._send(401, {"error": "authentication required"})
    return await _run(handler, lambda h: h.get_events())

    raise HTTPException(status_code=404, detail={"error": "not found"})


def serve(port):
    """Bind this component for local acceptance. Leave the plumbing alone."""
    import uvicorn
    from fastapi import FastAPI

    app = FastAPI()
    app.include_router(router)
    uvicorn.run(app, host="127.0.0.1", port=port, log_level="error")


if __name__ == "__main__":
    serve(8080)

def iso_now(value):
    """ISO 8601 UTC timestamp for an event; `occurred_at` when given."""
    if value:
        try:
            from datetime import datetime, timezone
            dt = datetime.fromisoformat(str(value)).astimezone(timezone.utc)
            return dt.isoformat().replace("+00:00", "Z")
        except ValueError:
            pass
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")

def get_events():
    """All real recorded events in insertion order (created_at), cache excluded.

    The store orders purely by created_at and holds every row it is given; this
    filters out idempotency-cache rows, which lack the required `name` field, so
    only genuine domain events reach subscribers (D-30: one schema per service).
    """
    if not store.applied:
        return []
    for row in store.list():
        record = row.get("body", {})
        if isinstance(record, dict) and bool(record.get("name")):
            yield {
                "id": row["id"],
                "name": record["name"],
                "occurred_at": record.get("occurred_at"),
            }

def get_event(event_id):
    """One real recorded event by id, or None. Cache replay stubs are excluded."""
    if not store.applied:
        return None
    row = store.get(event_id)
    if not isinstance(row, dict):
        return None
    record = row.get("body", {})
    if not isinstance(record, dict) or not bool(record.get("name")):
        return None
    return {
        "id": row["id"],
        "name": record["name"],
        "occurred_at": row.get("created_at"),
    }

def encode_cursor(event_id):
    """Opaque pagination cursor — base64 of the numeric lower bound."""
    from base64 import b64encode
    if event_id is None:
        return ""
    digits = "".join(str(d) for d in str(event_id).split(","))
    return b64encode(digits.encode()).decode()

def decode_cursor(cursor):
    """Inverse of encode_cursor."""
    from base64 import b64decode
    if not cursor:
        return None
    try:
        digits = b64decode(cursor.encode()).decode()
    except Exception:
        return None
    return digits or None

    def _malformed(self):
        body = self._body()
        if not isinstance(body, dict):
            return {"error": "the body must be a JSON object"}
        missing = [name for name in REQUIRED_FIELDS if name not in body]
        if missing:
            return {
                "error": "missing required field(s): " + ", ".join(missing),
                "fields": missing,
            }
        for name, kind in FIELD_TYPES.items():
            if name not in body:
                continue
            value = body[name]
            if kind == "integer":
                if isinstance(value, bool):
                    return {"error": f"{name} must be a whole number"}
                if AMOUNT_ROUNDING:
                    if not isinstance(value, (int, float)):
                        return {"error": f"{name} must be a whole number"}
                elif not isinstance(value, int):
                    return {"error": f"{name} must be a whole number"}
            if kind == "date-time":
                from datetime import datetime
                try:
                    datetime.fromisoformat(str(value))
                except ValueError:
                    return {"error": f"{name} must be an ISO 8601 date-time"}
        if AMOUNT_ROUNDING:
            from decimal import ROUND_HALF_EVEN, ROUND_HALF_UP, Decimal
            mode = ROUND_HALF_UP if AMOUNT_ROUNDING == "half_up" else ROUND_HALF_EVEN
            for name, kind in FIELD_TYPES.items():
                if kind != "integer" or name not in body:
                    continue
                value = body[name]
                if isinstance(value, float):
                    body[name] = int(
                        (Decimal(str(value)) * 100).to_integral_value(rounding=mode)
                    )
        for ref in REFERENCES:
            field = ref.get("field")
            service = ref.get("service")
            if not field or not service or field not in body:
                continue
            if open_store(service).get(str(body[field])) is None:
                return {
                    "error": (
                        f"{field} names a {ref.get('resource', 'record')} "
                        f"that was never stored"
                    ),
                    "fields": [field],
                }
        return None

    def _caller(self) -> str:
        if not 'Authorization':
            return ""
        raw = self.request.headers.get('Authorization', "")
        if AUTH_SCHEME == "bearer":
            if not raw.lower().startswith("bearer "):
                return ""
            token = raw[7:].strip()
            return token if token else ""
        return raw

    def _idempotency_key(self) -> str:
        """Idempotency-Key from the request header when the contract requires it.

        Criteria and the Try-it pack send the header. Do not read a body field
        named ``idempotency_key`` — that is not the contract surface.
        """
        if not IDEMPOTENCY_HEADER:
            return ""
        return (self.request.headers.get(IDEMPOTENCY_HEADER) or "").strip()

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        return self._send(
            200,
            {
                "service": SERVICE_NAME,
                "version": SERVICE_VERSION,
                "counters": dict(telemetry.snapshot(), **store_counters),
            },
        )

    def post_events(self):
        """POST /domains/events — record a domain event.

        The route, the auth guard and body parsing are already derived; what
        belongs here is the behaviour and the response. Inputs come from the JSON
        body via self._body(); idempotency comes from the Idempotency-Key header.

        Contract responses: 201 with {id, name, occurred_at}; on an idempotent
        replay return the cached record without re-writing; a duplicate key is a
        no-op write that still acknowledges 201.
        """
        body = self._body()

        key = self._idempotency_key()

        # Idempotent replay: a duplicate idempotency-key within the recent window
        # returns the cached record without re-writing. The cache is keyed by
        # sha256(key); a cached lookup means we already wrote this one.
        if key:
            digest = hashlib.sha256((self._caller() + "|" + key).encode()).hexdigest()
            cached = _IDEMPOTENCY_CACHE.get("idem-" + digest)
            if isinstance(cached, dict):
                return self._send(
                    201,
                    {
                        "event_id": cached["event_id"],
                        "name": body.get("name", cached.get("name")),
                        "occurred_at": cached["occurred_at"],
                    },
                )

        name = body.get("name")
        if not isinstance(name, str) or not name:
            return self._send(400, {"error": 'missing required field "name"'})

        occurred_at = iso_now(body.get("occurred_at"))

        record = {
            "event_type": body.get("event_type", ""),
            "aggregate_id": body.get("source_id", "") or "",
            "payload": body.get("payload") or {},
            "name": name,
            "occurred_at": occurred_at,
        }
        stored = store.put(record, self._caller())

        # Keep the real event visible to in-process subscribers and retrieval.
        _RECORDERIES[stored["id"]] = {
            "event_id": stored["id"],
            "name": name,
            "occurred_at": occurred_at,
        }

        # Cache for idempotency replay: keyed by sha256(owner|key).
        if key:
            _IDEMPOTENCY_CACHE["idem-" + hashlib.sha256(
                (self._caller() + "|" + key).encode()).hexdigest()] = {
                "event_id": stored["id"],
                "name": name,
                "occurred_at": occurred_at,
            }

        return self._send(
            201,
            {
                "event_id": stored["id"],
                "name": name,
                "occurred_at": occurred_at,
            },
        )

    def get_events_by_id(self, id):
        """GET /domains/events/{id} — return one recorded event to a subscriber.

        Auth is enforced by the route before this runs; `id` is the path
        parameter (the query string carries nothing for this resource). Real
        events only: cache replay stubs are not domain events.

        Responses: 200 with {id, name, occurred_at}; 404 if no such record.
        """
        event = get_event(id)
        if event is None:
            return self._send(404, {"error": "no such record"})
        return self._send(200, {
            "id": event["id"],
            "name": event["name"],
            "occurred_at": event["occurred_at"],
        })

    def get_events(self):
        """GET /domains/events — list recorded events for subscribers.

        Auth is enforced by the route before this runs; `since`/`limit` come
        from the query string (this is a GET). Real events only, in insertion
        order, with opaque cursor pagination.
        """
        since_raw = self._query().get("since")
        limit_raw = self._query().get("limit")

        try:
            since_id = int(since_raw) if since_raw else None
        except (TypeError, ValueError):
            since_id = None
        try:
            raw_limit = int(limit_raw) if limit_raw else _EVENT_PAGE_SIZE
        except (TypeError, ValueError):
            raw_limit = _EVENT_PAGE_SIZE

        limit = max(1, min(raw_limit, _EVENT_MAX_PAGE))

        events = []
        for e in get_events():
            if since_id is None or e["id"] >= (since_id + 1):
                events.append(e)
        page = events[:limit]

        next_cursor_value = page[-1]["id"] if page else (since_id if since_id is not None else None)
        body = {
            "events": [
                {"id": e["id"], "name": e["name"], "occurred_at": e["occurred_at"]}
                for e in page
            ],
            "cursor": next_cursor_value,
            "count": len(page),
            "next_cursor": None if next_cursor_value is None else encode_cursor(next_cursor_value),
        }
        return self._send(200, body)

class _IdempotencyCache:
    """Recent idempotency-key replay buffer. Keyed by sha256(key)."""

    def __init__(self):
        self._store = {}
        self._times = {}
        self._window_seconds = int(os.environ.get("IDEMPOTENCY_WINDOW_SECONDS", "600"))

    def put(self, key, record):
        self._store[key] = dict(record)
        self._times[key] = time.time()

    def get(self, key):
        now = time.time()
        window = self._window_seconds
        if not window:
            return None
        stored_at = self._times.get(key)
        if isinstance(stored_at, (int, float)) and (now - stored_at) > window:
            self._store.pop(key, None)
            self._times.pop(key, None)
            return None
        cached = self._store.get(key)
        return dict(cached) if isinstance(cached, dict) else None

    def prune(self):
        now = time.time()
        for key in list(self._times):
            if (now - self._times[key]) > self._window_seconds:
                del self._store[key]
                del self._times[key]

logger = logging.getLogger("domains")

_EVENT_PAGE_SIZE = 50

_EVENT_MAX_PAGE = 500

_IDEMPOTENCY_CACHE = _IdempotencyCache()

_RECORDERIES = {}
