"""the system shall expose GET /oauth/authorize that issues an authorization code when client_id exists and the resource owner approves.

Generated by The Factory from its requirement graph.
"""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse, Response

import telemetry
from store import StoreUnavailable, open_store
from store import counters as store_counters

SERVICE_NAME = 'oauth'
SERVICE_VERSION = "1.0.0"
ENTITY = 'oauth'
BASE_PATH = '/oauth'
RETENTION_DAYS = None
RECORD_FIELDS = ['client_id']
STORE_ATTEMPTS = 1
IDENTITY_FIELD = None
UNIQUE_FIELDS = []
REQUIRED_FIELDS = []
FIELD_TYPES = {}
AMOUNT_ROUNDING = None
REFERENCES = []
AUTH_SCHEME = 'plain'
IDEMPOTENCY_HEADER = ''

store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS)
_IDEMPOTENCY_KEYS = {}


class Handler:
    """Contract plumbing and behaviour handlers. Complete the TODO methods only."""

    def __init__(self, request: Request):
        self.request = request
        self._parsed_body = None

    async def load_body(self):
        if self._parsed_body is None:
            try:
                self._parsed_body = await self.request.json()
            except Exception:
                self._parsed_body = {}
        return self._parsed_body

    def _send(self, status, payload=None):
        if status == 204:
            response = Response(status_code=204)
        else:
            response = JSONResponse(status_code=status, content=payload)
        telemetry.count(f"http_{status}")
        operation = self._operation()
        if operation:
            telemetry.count(
                f"{operation}.{'error' if status >= 400 else 'ok'}"
            )
        return response

    def _operation(self):
        path = self.request.url.path.rstrip("/")
        collection = path == BASE_PATH.rstrip("/")
        verb = {"POST": "store", "PUT": "store", "PATCH": "update", "DELETE": "delete"}.get(
            self.request.method, "list" if collection else "read"
        )
        return f"{ENTITY}.{verb}" if ENTITY else ""

    def _body(self) -> dict:
        return self._parsed_body if self._parsed_body is not None else {}

    def _query(self) -> dict:
        """Query-string fields for GET/HEAD — not a JSON body."""
        return {key: value for key, value in self.request.query_params.multi_items()}

    def _malformed(self):
        body = self._body()
        if not isinstance(body, dict):
            return {"error": "the body must be a JSON object"}
        missing = [name for name in REQUIRED_FIELDS if name not in body]
        if missing:
            return {
                "error": "missing required field(s): " + ", ".join(missing),
                "fields": missing,
            }
        for name, kind in FIELD_TYPES.items():
            if name not in body:
                continue
            value = body[name]
            if kind == "integer":
                if isinstance(value, bool):
                    return {"error": f"{name} must be a whole number"}
                if AMOUNT_ROUNDING:
                    if not isinstance(value, (int, float)):
                        return {"error": f"{name} must be a whole number"}
                elif not isinstance(value, int):
                    return {"error": f"{name} must be a whole number"}
            if kind == "date-time":
                from datetime import datetime
                try:
                    datetime.fromisoformat(str(value))
                except ValueError:
                    return {"error": f"{name} must be an ISO 8601 date-time"}
        if AMOUNT_ROUNDING:
            from decimal import ROUND_HALF_EVEN, ROUND_HALF_UP, Decimal
            mode = ROUND_HALF_UP if AMOUNT_ROUNDING == "half_up" else ROUND_HALF_EVEN
            for name, kind in FIELD_TYPES.items():
                if kind != "integer" or name not in body:
                    continue
                value = body[name]
                if isinstance(value, float):
                    body[name] = int(
                        (Decimal(str(value)) * 100).to_integral_value(rounding=mode)
                    )
        for ref in REFERENCES:
            field = ref.get("field")
            service = ref.get("service")
            if not field or not service or field not in body:
                continue
            if open_store(service).get(str(body[field])) is None:
                return {
                    "error": (
                        f"{field} names a {ref.get('resource', 'record')} "
                        f"that was never stored"
                    ),
                    "fields": [field],
                }
        return None

    def _caller(self) -> str:
        if not '':
            return ""
        raw = self.request.headers.get('', "")
        if AUTH_SCHEME == "bearer":
            if not raw.lower().startswith("bearer "):
                return ""
            token = raw[7:].strip()
            return token if token else ""
        return raw

    def _idempotency_key(self) -> str:
        """Idempotency-Key from the request header when the contract requires it.

        Criteria and the Try-it pack send the header. Do not read a body field
        named ``idempotency_key`` — that is not the contract surface.
        """
        if not IDEMPOTENCY_HEADER:
            return ""
        return (self.request.headers.get(IDEMPOTENCY_HEADER) or "").strip()

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        return self._send(
            200,
            {
                "service": SERVICE_NAME,
                "version": SERVICE_VERSION,
                "counters": dict(telemetry.snapshot(), **store_counters),
            },
        )

    def get_authorize(self):
        """Issue an authorization code for a registered client.

        Query (or body) must name client_id and redirect_uri. Unknown
        clients and non-matching redirect_uri values answer 400 with
        an error field. A match stores a one-time code and returns
        200 with code + location (harness-friendly; 302 also fine).
        """
        q = self._query() if hasattr(self, '_query') else {}
        body = self._body() if not q.get('client_id') else {}
        if not isinstance(body, dict):
            body = {}
        client_id = (q.get('client_id') or body.get('client_id') or '').strip()
        redirect_uri = (q.get('redirect_uri') or body.get('redirect_uri') or '').strip()
        if not client_id:
            return self._send(400, {"error": "invalid_request"})
        clients = open_store(
            "oauth_clients", None,
            ["client_id", "client_secret", "redirect_uri", "redirect_uris"],
            STORE_ATTEMPTS,
        )
        record = clients.get(client_id)
        if record is None:
            return self._send(400, {"error": "invalid_client"})
        allowed = record.get('redirect_uris') or record.get('redirect_uri') or ''
        if isinstance(allowed, str) and allowed.startswith('['):
            try:
                import json as _json
                allowed = _json.loads(allowed)
            except Exception:
                pass
        if redirect_uri and allowed:
            ok = (
                redirect_uri in allowed
                if isinstance(allowed, (list, tuple))
                else redirect_uri == allowed or redirect_uri in str(allowed)
            )
            if not ok:
                return self._send(400, {"error": "invalid_redirect_uri"})
        code = secrets.token_urlsafe(24)
        store.put(
            {"id": code, "code": code, "client_id": client_id,
             "redirect_uri": redirect_uri,
             "issued_at": __import__("store").clock.now()},
            owner=self._caller() or '',
        )
        sep = '&' if '?' in redirect_uri else '?'
        location = (
            f'{redirect_uri}{sep}code={code}' if redirect_uri else ''
        )
        return self._send(200, {
            "code": code,
            "authorization_code": code,
            "location": location,
        })



router = APIRouter()


async def _run(handler, call):
    try:
        return call(handler)
    except StoreUnavailable as error:
        return handler._send(503, {"error": str(error)})
    except Exception as error:  # noqa: BLE001
        return handler._send(500, {"error": str(error)})


@router.get("/health")
async def _route_health(request: Request):
    handler = Handler(request)
    return await _run(handler, lambda h: h.health())

@router.get('/oauth/authorize')
async def _route_get_authorize(request: Request):
    handler = Handler(request)
    return await _run(handler, lambda h: h.get_authorize())

    raise HTTPException(status_code=404, detail={"error": "not found"})


def serve(port):
    """Bind this component for local acceptance. Leave the plumbing alone."""
    import uvicorn
    from fastapi import FastAPI

    app = FastAPI()
    app.include_router(router)
    uvicorn.run(app, host="127.0.0.1", port=port, log_level="error")


if __name__ == "__main__":
    serve(8080)
