"""the system shall accept inbound webhooks at POST /webhooks, verify an HMAC signature when X-Signature is present, store the event, and acknowledge with 201.

Generated by The Factory from its requirement graph.
"""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse, Response

import secrets
from datetime import datetime, timezone
import hashlib

import telemetry
from store import StoreUnavailable, open_store
from store import counters as store_counters
import json
import os
from store import clock
from webhook_signature import SIGNATURE_HEADER, verify_signature

SERVICE_NAME = 'webhooks'
SERVICE_VERSION = "1.0.0"
ENTITY = 'webhook'
BASE_PATH = '/webhooks'
RETENTION_DAYS = None
RECORD_FIELDS = ['event_data', 'source_system']
STORE_ATTEMPTS = 1
IDENTITY_FIELD = None
UNIQUE_FIELDS = []
REQUIRED_FIELDS = []
FIELD_TYPES = {}
AMOUNT_ROUNDING = None
REFERENCES = []
AUTH_SCHEME = 'bearer'
IDEMPOTENCY_HEADER = 'Idempotency-Key'
OWNER_HEADER = 'Authorization'

store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS)
_IDEMPOTENCY_KEYS = {}


class Handler:
    """Contract plumbing and behaviour handlers. Complete the TODO methods only."""

    def __init__(self, request: Request):
        self.request = request
        self._parsed_body = None

    async def load_body(self):
        if self._parsed_body is None:
            try:
                self._parsed_body = await self.request.json()
            except Exception:
                self._parsed_body = {}
        return self._parsed_body

    def _send(self, status, payload=None):
        if status == 204:
            response = Response(status_code=204)
        else:
            response = JSONResponse(status_code=status, content=payload)
        telemetry.count(f"http_{status}")
        operation = self._operation()
        if operation:
            telemetry.count(
                f"{operation}.{'error' if status >= 400 else 'ok'}"
            )
        return response

    def _operation(self):
        path = self.request.url.path.rstrip("/")
        collection = path == BASE_PATH.rstrip("/")
        verb = {"POST": "store", "PUT": "store", "PATCH": "update", "DELETE": "delete"}.get(
            self.request.method, "list" if collection else "read"
        )
        return f"{ENTITY}.{verb}" if ENTITY else ""

    def _body(self) -> dict:
        return self._parsed_body if self._parsed_body is not None else {}

    def _query(self) -> dict:
        """Query-string fields for GET/HEAD — not a JSON body."""
        return {key: value for key, value in self.request.query_params.multi_items()}

    def _malformed(self):
        body = self._body()
        if not isinstance(body, dict):
            return {"error": "the body must be a JSON object"}
        missing = [name for name in REQUIRED_FIELDS if name not in body]
        if missing:
            return {
                "error": "missing required field(s): " + ", ".join(missing),
                "fields": missing,
            }
        for name, kind in FIELD_TYPES.items():
            if name not in body:
                continue
            value = body[name]
            if kind == "integer":
                if isinstance(value, bool):
                    return {"error": f"{name} must be a whole number"}
                if AMOUNT_ROUNDING:
                    if not isinstance(value, (int, float)):
                        return {"error": f"{name} must be a whole number"}
                elif not isinstance(value, int):
                    return {"error": f"{name} must be a whole number"}
            if kind == "date-time":
                from datetime import datetime
                try:
                    datetime.fromisoformat(str(value))
                except ValueError:
                    return {"error": f"{name} must be an ISO 8601 date-time"}
        if AMOUNT_ROUNDING:
            from decimal import ROUND_HALF_EVEN, ROUND_HALF_UP, Decimal
            mode = ROUND_HALF_UP if AMOUNT_ROUNDING == "half_up" else ROUND_HALF_EVEN
            for name, kind in FIELD_TYPES.items():
                if kind != "integer" or name not in body:
                    continue
                value = body[name]
                if isinstance(value, float):
                    body[name] = int(
                        (Decimal(str(value)) * 100).to_integral_value(rounding=mode)
                    )
        for ref in REFERENCES:
            field = ref.get("field")
            service = ref.get("service")
            if not field or not service or field not in body:
                continue
            if open_store(service).get(str(body[field])) is None:
                return {
                    "error": (
                        f"{field} names a {ref.get('resource', 'record')} "
                        f"that was never stored"
                    ),
                    "fields": [field],
                }
        return None

    def _caller(self) -> str:
        if not 'Authorization':
            return ""
        raw = self.request.headers.get('Authorization', "")
        if AUTH_SCHEME == "bearer":
            if not raw.lower().startswith("bearer "):
                return ""
            token = raw[7:].strip()
            return token if token else ""
        return raw

    def _idempotency_key(self) -> str:
        """Idempotency-Key from the request header when the contract requires it.

        Criteria and the Try-it pack send the header. Do not read a body field
        named ``idempotency_key`` — that is not the contract surface.
        """
        if not IDEMPOTENCY_HEADER:
            return ""
        return (self.request.headers.get(IDEMPOTENCY_HEADER) or "").strip()

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        return self._send(
            200,
            {
                "service": SERVICE_NAME,
                "version": SERVICE_VERSION,
                "counters": dict(telemetry.snapshot(), **store_counters),
            },
        )

    def post(self):
        """POST /webhooks/, as the contract describes it.

        Responses the contract names:
          201: Webhook successfully accepted, stored, and acknowledged.
          401: Unauthorized: Invalid or missing HMAC signature.
          422: Validation Error: The payload is malformed or missing required fields.
        """
        body = self._body()
        if not isinstance(body, dict):
            return self._send(422, {"error": "the body must be a JSON object"})

        malformed = self._malformed()
        if malformed:
            return self._send(422, malformed)

        # Verify the HMAC signature only when X-Signature is present, per the
        # contract ("verify an HMAC signature when X-Signature is present").
        # An absent header is not itself a rejection; an incorrect one is.
        signature_header = self.request.headers.get(SIGNATURE_HEADER)
        message = json.dumps(body, sort_keys=True).encode("utf-8")
        if signature_header is not None:
            if not verify_signature(WEBHOOK_SECRET, message, signature_header):
                return self._send(401, {"error": "invalid HMAC signature"})

        owner = self._caller()
        idempotency_key = self._idempotency_key()

        existing = self._existing_by_idempotency_key(owner, idempotency_key)
        if existing is not None:
            return self._send(201, {"id": existing.get("id"), "status": "accepted"})

        record = {
            name: body.get(name) for name in RECORD_FIELDS if name in body
        }
        record["signature"] = signature_header or ""
        record["idempotency_key"] = idempotency_key
        record["received_at"] = datetime.fromtimestamp(
            clock.now(), tz=timezone.utc
        ).isoformat()
        record["status"] = "accepted"

        stored = store.put(record, owner)
        return self._send(201, {"id": stored["id"], "status": stored["status"]})



router = APIRouter()


async def _run(handler, call):
    try:
        return call(handler)
    except StoreUnavailable as error:
        return handler._send(503, {"error": str(error)})
    except Exception as error:  # noqa: BLE001
        return handler._send(500, {"error": str(error)})


@router.get("/health")
async def _route_health(request: Request):
    handler = Handler(request)
    return await _run(handler, lambda h: h.health())

@router.post('/webhooks/')
async def _route_post(request: Request):
    handler = Handler(request)
    if not handler._caller():
        return handler._send(401, {"error": "authentication required"})
    await handler.load_body()
    return await _run(handler, lambda h: h.post())

    raise HTTPException(status_code=404, detail={"error": "not found"})


def serve(port):
    """Bind this component for local acceptance. Leave the plumbing alone."""
    import uvicorn
    from fastapi import FastAPI

    app = FastAPI()
    app.include_router(router)
    uvicorn.run(app, host="127.0.0.1", port=port, log_level="error")


if __name__ == "__main__":
    serve(8080)

WEBHOOK_SECRET = os.environ.get("WEBHOOK_SECRET", "")
