"""the system shall accept POST requests to a webhook endpoint, validate HMAC signatures when provided in the request, and reject requests with invalid signatures.

Generated by The Factory from its requirement graph.
"""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse, Response

import telemetry
from store import StoreUnavailable, open_store
from store import counters as store_counters
import logging
from .signature import compute_hmac_sha256, constant_time_compare, extract_signature_header
import os

SERVICE_NAME = 'webhooks'
SERVICE_VERSION = "1.0.0"
ENTITY = 'webhook'
BASE_PATH = '/webhooks'
RETENTION_DAYS = None
RECORD_FIELDS = []
STORE_ATTEMPTS = 1
IDENTITY_FIELD = None
UNIQUE_FIELDS = []
REQUIRED_FIELDS = []
FIELD_TYPES = {}
AMOUNT_ROUNDING = None
REFERENCES = []
AUTH_SCHEME = 'plain'
IDEMPOTENCY_HEADER = ''
OWNER_HEADER = 'X-Signature'

store = open_store(SERVICE_NAME, RETENTION_DAYS, RECORD_FIELDS, STORE_ATTEMPTS)
_IDEMPOTENCY_KEYS = {}


class Handler:
    """Contract plumbing and behaviour handlers. Complete the TODO methods only."""

    def __init__(self, request: Request):
        self.request = request
        self._parsed_body = None

    async def load_body(self):
        if self._parsed_body is None:
            try:
                raw = await self.request.body()
            except Exception:
                raw = b""
            self._raw_body = raw or b""
            try:
                import json as _json
                self._parsed_body = _json.loads(self._raw_body) if self._raw_body else {}
            except Exception:
                self._parsed_body = {}
        return self._parsed_body

    def _send(self, status, payload=None):
        if status == 204:
            response = Response(status_code=204)
        else:
            response = JSONResponse(status_code=status, content=payload)
        telemetry.count(f"http_{status}")
        operation = self._operation()
        if operation:
            telemetry.count(
                f"{operation}.{'error' if status >= 400 else 'ok'}"
            )
        return response

    def _operation(self):
        path = self.request.url.path.rstrip("/")
        collection = path == BASE_PATH.rstrip("/")
        verb = {"POST": "store", "PUT": "store", "PATCH": "update", "DELETE": "delete"}.get(
            self.request.method, "list" if collection else "read"
        )
        return f"{ENTITY}.{verb}" if ENTITY else ""

    def _body(self) -> dict:
        return self._parsed_body if self._parsed_body is not None else {}

    def _query(self) -> dict:
        """Query-string fields for GET/HEAD — not a JSON body."""
        return {key: value for key, value in self.request.query_params.multi_items()}

    def _malformed(self):
        body = self._body()
        if not isinstance(body, dict):
            return {"error": "the body must be a JSON object"}
        missing = [name for name in REQUIRED_FIELDS if name not in body]
        if missing:
            return {
                "error": "missing required field(s): " + ", ".join(missing),
                "fields": missing,
            }
        for name, kind in FIELD_TYPES.items():
            if name not in body:
                continue
            value = body[name]
            if kind == "integer":
                if isinstance(value, bool):
                    return {"error": f"{name} must be a whole number"}
                if AMOUNT_ROUNDING:
                    if not isinstance(value, (int, float)):
                        return {"error": f"{name} must be a whole number"}
                elif not isinstance(value, int):
                    return {"error": f"{name} must be a whole number"}
            if kind == "date-time":
                from datetime import datetime
                try:
                    datetime.fromisoformat(str(value))
                except ValueError:
                    return {"error": f"{name} must be an ISO 8601 date-time"}
        if AMOUNT_ROUNDING:
            from decimal import ROUND_HALF_EVEN, ROUND_HALF_UP, Decimal
            mode = ROUND_HALF_UP if AMOUNT_ROUNDING == "half_up" else ROUND_HALF_EVEN
            for name, kind in FIELD_TYPES.items():
                if kind != "integer" or name not in body:
                    continue
                value = body[name]
                if isinstance(value, float):
                    body[name] = int(
                        (Decimal(str(value)) * 100).to_integral_value(rounding=mode)
                    )
        for ref in REFERENCES:
            field = ref.get("field")
            service = ref.get("service")
            if not field or not service or field not in body:
                continue
            if open_store(service).get(str(body[field])) is None:
                return {
                    "error": (
                        f"{field} names a {ref.get('resource', 'record')} "
                        f"that was never stored"
                    ),
                    "fields": [field],
                }
        return None

    def _caller(self) -> str:
        if not 'X-Signature':
            return ""
        raw = self.request.headers.get('X-Signature', "")
        if AUTH_SCHEME == "bearer":
            if not raw.lower().startswith("bearer "):
                return ""
            token = raw[7:].strip()
            return token if token else ""
        return raw

    def _signature_ok(self) -> bool:
        header_name = 'X-Signature'
        if not header_name or "signature" not in header_name.lower():
            return True
        import hashlib
        import hmac
        import os
        presented = (self.request.headers.get(header_name) or "").strip()
        if not presented:
            return False
        secret = os.environ.get("WEBHOOK_SECRET", "factory-webhook-secret")
        raw = getattr(self, "_raw_body", b"") or b""
        digest = hmac.new(secret.encode("utf-8"), raw, hashlib.sha256).hexdigest()
        return hmac.compare_digest("sha256=" + digest, presented)

    def _idempotency_key(self) -> str:
        """Idempotency-Key from the request header when the contract requires it.

        Criteria and the Try-it pack send the header. Do not read a body field
        named ``idempotency_key`` — that is not the contract surface.
        """
        if not IDEMPOTENCY_HEADER:
            return ""
        return (self.request.headers.get(IDEMPOTENCY_HEADER) or "").strip()

    def health(self):
        """The contract's /health. Already correct; leave it alone."""
        return self._send(
            200,
            {
                "service": SERVICE_NAME,
                "version": SERVICE_VERSION,
                "counters": dict(telemetry.snapshot(), **store_counters),
            },
        )

    def post(self):
        """POST /webhooks/, as the contract describes it.

        The route, the auth guard and the path parameters are already
        derived; what belongs here is the behaviour and the response.

        X-Signature must be present and valid before any business logic runs:
        validate first, persist only on success, log every rejection for audit.

        Responses the contract names:
          200: Webhook processed successfully and signature validated.
          401: Invalid HMAC signature provided in the request headers.
        """
        # A missing X-Signature is the same as an invalid one here; reject both
        # before we persist anything or advance to downstream processing. The
        # route already refuses a blank header with its own guard, but validate
        # again so Handler.post() stands on its own (unit tests call it directly).
        signature = extract_signature_header(self.request)
        if not signature:
            log.warning("POST /webhooks/ refused: no X-Signature header")
            return self._send(401, {"error": "an owner is required"})

        # Sign the exact bytes the caller sent, then compare in constant time so
        # a timing side-channel cannot distinguish valid from invalid digests.
        # Hash the raw body captured once (load_body consumed request.body());
        # reading it again here would yield b"" and break every signature.
        raw = getattr(self, "_raw_body", b"") or b""
        secret = os.environ.get("WEBHOOK_SECRET", "factory-webhook-secret")
        # The header carries the "sha256=" prefix (see webhook_signature.sign_body
        # and the route guard); match it so a correctly signed request validates.
        expected = "sha256=" + compute_hmac_sha256(raw, secret)
        if not constant_time_compare(expected, signature):
            log.warning("POST /webhooks/ rejected: invalid X-Signature")
            return self._send(401, {"error": "invalid signature"})

        body = self._body()

        # Replay detection for opt_allow_duplicates. The option is to *allow*
        # replays rather than reject them; we still record the event id (or its
        # timestamp) so a duplicate can be recognised from store.list later, but
        # this endpoint returns success either way.
        _record_seen(body)

        stored = store.put(body, owner=signature)
        log.info("POST /webhooks/ accepted: id=%s", stored.get("id"))
        return self._send(200, {"accepted": True, "id": stored.get("id")})



router = APIRouter()


async def _run(handler, call):
    try:
        return call(handler)
    except StoreUnavailable as error:
        return handler._send(503, {"error": str(error)})
    except Exception as error:  # noqa: BLE001
        return handler._send(500, {"error": str(error)})


@router.get("/health")
async def _route_health(request: Request):
    handler = Handler(request)
    return await _run(handler, lambda h: h.health())

@router.post('/webhooks/')
async def _route_post(request: Request):
    handler = Handler(request)
    await handler.load_body()
    if not handler._signature_ok():
        return handler._send(401, {"error": "invalid signature"})
    await handler.load_body()
    return await _run(handler, lambda h: h.post())

    raise HTTPException(status_code=404, detail={"error": "not found"})


def serve(port):
    """Bind this component for local acceptance. Leave the plumbing alone."""
    import uvicorn
    from fastapi import FastAPI

    app = FastAPI()
    app.include_router(router)
    uvicorn.run(app, host="127.0.0.1", port=port, log_level="error")


if __name__ == "__main__":
    serve(8080)

def _record_seen(body):
    """Record a webhook event id or timestamp to detect replays."""
    if not opt_allow_duplicates:
        return
    key = (body.get("id"), body.get("event_id"))
    if key in _SEEN:
        log.info("POST /webhooks/ duplicate seen: %s", key)
    else:
        _SEEN.add(key)

log = logging.getLogger("webhooks.webhook")

opt_allow_duplicates = True

_SEEN = set()  # module-level, so every request in this process shares it
