"""HMAC-SHA256 signature computation and comparison for the webhook surface.

Generated by The Factory from its build plan: helpers named in
`build_plan.helpers`, so each one is a function the POST handler calls rather
than behaviour it invents.
"""

import hashlib
import hmac
import logging


log = logging.getLogger("webhooks.signature")


def compute_hmac_sha256(body: bytes, secret: str) -> str:
    """Generate the HMAC-SHA256 hex digest of a raw body."""
    return hmac.new(
        secret.encode("utf-8"), body, hashlib.sha256,
    ).hexdigest()


def constant_time_compare(a: str, b: str) -> bool:
    """Compare two signatures in constant time to prevent timing attacks."""
    return hmac.compare_digest(a, b)


def extract_signature_header(request) -> str:
    """Retrieve the X-Signature header or raise so no business logic runs.

    Called before any downstream processing; a missing header is the same as
    an invalid one for this surface.
    """
    return request.headers.get("X-Signature", "")

